package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;
import java.util.concurrent.CompletionStage;

import com.tencent.aimedia.VideoStructureProtocol.CreateVideoStructureTaskRequest;
import com.tencent.aimedia.VideoStructureProtocol.CreateVideoStructureTaskResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAICatalogTaskDataRequest;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAICatalogTaskDataResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.videostructure.AICatalog")
public interface AICatalogAsyncAPI {

    /**
     * CreateAICatalogTask
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link CreateVideoStructureTaskResponse}
     */
    @TRpcMethod(name = "CreateAICatalogTask")
    CompletionStage<CreateVideoStructureTaskResponse> createAICatalogTask(RpcContext context, CreateVideoStructureTaskRequest request);

    /**
     * DescribeAICatalogTaskData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeAICatalogTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeAICatalogTaskData")
    CompletionStage<DescribeAICatalogTaskDataResponse> describeAICatalogTaskData(RpcContext context, DescribeAICatalogTaskDataRequest request);
}