package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.VideoStructureProtocol.CreateVideoStructureTaskRequest;
import com.tencent.aimedia.VideoStructureProtocol.CreateVideoStructureTaskResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagTaskDataRequest;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagTaskDataResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagAudioTaskDataResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagImageTaskDataResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagTextTaskDataResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeVideoShotCoverRequest;
import com.tencent.aimedia.VideoStructureProtocol.DescribeVideoShotCoverResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.videostructure.AITag")
public interface AITagAPI {

    /**
     * CreateAITagTask
     *
     * @param context context
     * @param request request
     * @return {@link CreateVideoStructureTaskResponse}
     */
    @TRpcMethod(name = "CreateAITagTask")
    CreateVideoStructureTaskResponse createAITagTask(RpcContext context, CreateVideoStructureTaskRequest request);

    /**
     * DescribeAITagTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribeAITagTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeAITagTaskData")
    DescribeAITagTaskDataResponse describeAITagTaskData(RpcContext context, DescribeAITagTaskDataRequest request);

    /**
     * DescribeAITagAudioTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribeAITagAudioTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeAITagAudioTaskData")
    DescribeAITagAudioTaskDataResponse describeAITagAudioTaskData(RpcContext context, DescribeAITagTaskDataRequest request);

    /**
     * DescribeAITagImageTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribeAITagImageTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeAITagImageTaskData")
    DescribeAITagImageTaskDataResponse describeAITagImageTaskData(RpcContext context, DescribeAITagTaskDataRequest request);

    /**
     * DescribeAITagTextTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribeAITagTextTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeAITagTextTaskData")
    DescribeAITagTextTaskDataResponse describeAITagTextTaskData(RpcContext context, DescribeAITagTaskDataRequest request);

    /**
     * DescribeVideoShotCover
     *
     * @param context context
     * @param request request
     * @return {@link DescribeVideoShotCoverResponse}
     */
    @TRpcMethod(name = "DescribeVideoShotCover")
    DescribeVideoShotCoverResponse describeVideoShotCover(RpcContext context, DescribeVideoShotCoverRequest request);
}