package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;
import java.util.concurrent.CompletionStage;

import com.tencent.aimedia.VideoStructureProtocol.CreateVideoStructureTaskRequest;
import com.tencent.aimedia.VideoStructureProtocol.CreateVideoStructureTaskResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagTaskDataRequest;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagTaskDataResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagAudioTaskDataResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagImageTaskDataResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeAITagTextTaskDataResponse;
import com.tencent.aimedia.VideoStructureProtocol.DescribeVideoShotCoverRequest;
import com.tencent.aimedia.VideoStructureProtocol.DescribeVideoShotCoverResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.videostructure.AITag")
public interface AITagAsyncAPI {

    /**
     * CreateAITagTask
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link CreateVideoStructureTaskResponse}
     */
    @TRpcMethod(name = "CreateAITagTask")
    CompletionStage<CreateVideoStructureTaskResponse> createAITagTask(RpcContext context, CreateVideoStructureTaskRequest request);

    /**
     * DescribeAITagTaskData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeAITagTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeAITagTaskData")
    CompletionStage<DescribeAITagTaskDataResponse> describeAITagTaskData(RpcContext context, DescribeAITagTaskDataRequest request);

    /**
     * DescribeAITagAudioTaskData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeAITagAudioTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeAITagAudioTaskData")
    CompletionStage<DescribeAITagAudioTaskDataResponse> describeAITagAudioTaskData(RpcContext context, DescribeAITagTaskDataRequest request);

    /**
     * DescribeAITagImageTaskData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeAITagImageTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeAITagImageTaskData")
    CompletionStage<DescribeAITagImageTaskDataResponse> describeAITagImageTaskData(RpcContext context, DescribeAITagTaskDataRequest request);

    /**
     * DescribeAITagTextTaskData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeAITagTextTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeAITagTextTaskData")
    CompletionStage<DescribeAITagTextTaskDataResponse> describeAITagTextTaskData(RpcContext context, DescribeAITagTaskDataRequest request);

    /**
     * DescribeVideoShotCover
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeVideoShotCoverResponse}
     */
    @TRpcMethod(name = "DescribeVideoShotCover")
    CompletionStage<DescribeVideoShotCoverResponse> describeVideoShotCover(RpcContext context, DescribeVideoShotCoverRequest request);
}