package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.AITagAnalyseProtocol.CommonRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.DescribeL1L2LabelsResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.CreateTagRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.CreateTagResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.ImportTagRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.ImportTagResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.DeleteTagRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.DeleteTagResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.ModifyTagRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.ModifyTagResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.DescribeTagsRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.DescribeTagsResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.CreateTagAnalysisTaskRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.CreateTagAnalysisTaskResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.DescribeTagAnalysisTaskDataRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.DescribeTagAnalysisTaskDataResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.DescribeTagFilesRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.DescribeTagFilesResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.DeleteTagFilesRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.DeleteTagFilesResponse;
import com.tencent.aimedia.AITagAnalyseProtocol.TagFileUrlRequest;
import com.tencent.aimedia.AITagAnalyseProtocol.TagFileUrlResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.aitaganalyse.AiTagAnalyse")
public interface AiTagAnalyseAPI {

    /**
     * DescribeL1L2Labels
     *
     * @param context context
     * @param request request
     * @return {@link DescribeL1L2LabelsResponse}
     */
    @TRpcMethod(name = "DescribeL1L2Labels")
    DescribeL1L2LabelsResponse describeL1L2Labels(RpcContext context, CommonRequest request);

    /**
     * CreateTag
     *
     * @param context context
     * @param request request
     * @return {@link CreateTagResponse}
     */
    @TRpcMethod(name = "CreateTag")
    CreateTagResponse createTag(RpcContext context, CreateTagRequest request);

    /**
     * ImportTag
     *
     * @param context context
     * @param request request
     * @return {@link ImportTagResponse}
     */
    @TRpcMethod(name = "ImportTag")
    ImportTagResponse importTag(RpcContext context, ImportTagRequest request);

    /**
     * DeleteTag
     *
     * @param context context
     * @param request request
     * @return {@link DeleteTagResponse}
     */
    @TRpcMethod(name = "DeleteTag")
    DeleteTagResponse deleteTag(RpcContext context, DeleteTagRequest request);

    /**
     * ModifyTag
     *
     * @param context context
     * @param request request
     * @return {@link ModifyTagResponse}
     */
    @TRpcMethod(name = "ModifyTag")
    ModifyTagResponse modifyTag(RpcContext context, ModifyTagRequest request);

    /**
     * DescribeTags
     *
     * @param context context
     * @param request request
     * @return {@link DescribeTagsResponse}
     */
    @TRpcMethod(name = "DescribeTags")
    DescribeTagsResponse describeTags(RpcContext context, DescribeTagsRequest request);

    /**
     * CreateTagAnalysisTask
     *
     * @param context context
     * @param request request
     * @return {@link CreateTagAnalysisTaskResponse}
     */
    @TRpcMethod(name = "CreateTagAnalysisTask")
    CreateTagAnalysisTaskResponse createTagAnalysisTask(RpcContext context, CreateTagAnalysisTaskRequest request);

    /**
     * DescribeTagAnalysisTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribeTagAnalysisTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeTagAnalysisTaskData")
    DescribeTagAnalysisTaskDataResponse describeTagAnalysisTaskData(RpcContext context, DescribeTagAnalysisTaskDataRequest request);

    /**
     * DescribeTagFiles
     *
     * @param context context
     * @param request request
     * @return {@link DescribeTagFilesResponse}
     */
    @TRpcMethod(name = "DescribeTagFiles")
    DescribeTagFilesResponse describeTagFiles(RpcContext context, DescribeTagFilesRequest request);

    /**
     * DeleteTagFiles
     *
     * @param context context
     * @param request request
     * @return {@link DeleteTagFilesResponse}
     */
    @TRpcMethod(name = "DeleteTagFiles")
    DeleteTagFilesResponse deleteTagFiles(RpcContext context, DeleteTagFilesRequest request);

    /**
     * GetTagFileUrl
     *
     * @param context context
     * @param request request
     * @return {@link TagFileUrlResponse}
     */
    @TRpcMethod(name = "GetTagFileUrl")
    TagFileUrlResponse getTagFileUrl(RpcContext context, TagFileUrlRequest request);
}