package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;
import java.util.concurrent.CompletionStage;

import com.tencent.aimedia.CustomFeatureProtocol.DescribeTextCategoriesRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeTextCategoriesResponse;
import com.tencent.aimedia.CustomFeatureProtocol.CreateCustomTextRequest;
import com.tencent.aimedia.CustomFeatureProtocol.CreateCustomTextResponse;
import com.tencent.aimedia.CustomFeatureProtocol.ModifyCustomTextRequest;
import com.tencent.aimedia.CustomFeatureProtocol.ModifyCustomTextResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeCustomTextsRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeCustomTextsResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeLastUpdateTimeRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeLastUpdateTimeResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DeleteCustomTextRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DeleteCustomTextResponse;
import com.tencent.aimedia.CustomFeatureProtocol.CreateFeatureRequest;
import com.tencent.aimedia.CustomFeatureProtocol.CreateFeatureResponse;
import com.tencent.aimedia.CustomFeatureProtocol.ModifyFeatureRequest;
import com.tencent.aimedia.CustomFeatureProtocol.ModifyFeatureResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeFeaturesRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeFeaturesResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DeleteFeatureRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DeleteFeatureResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.customfeature.CustomFeature")
public interface CustomFeatureAsyncAPI {

    /**
     * DescribeTextCategories
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeTextCategoriesResponse}
     */
    @TRpcMethod(name = "DescribeTextCategories")
    CompletionStage<DescribeTextCategoriesResponse> describeTextCategories(RpcContext context, DescribeTextCategoriesRequest request);

    /**
     * CreateCustomText
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link CreateCustomTextResponse}
     */
    @TRpcMethod(name = "CreateCustomText")
    CompletionStage<CreateCustomTextResponse> createCustomText(RpcContext context, CreateCustomTextRequest request);

    /**
     * ModifyCustomText
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link ModifyCustomTextResponse}
     */
    @TRpcMethod(name = "ModifyCustomText")
    CompletionStage<ModifyCustomTextResponse> modifyCustomText(RpcContext context, ModifyCustomTextRequest request);

    /**
     * DescribeCustomTexts
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeCustomTextsResponse}
     */
    @TRpcMethod(name = "DescribeCustomTexts")
    CompletionStage<DescribeCustomTextsResponse> describeCustomTexts(RpcContext context, DescribeCustomTextsRequest request);

    /**
     * DescribeLastUpdateTime
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeLastUpdateTimeResponse}
     */
    @TRpcMethod(name = "DescribeLastUpdateTime")
    CompletionStage<DescribeLastUpdateTimeResponse> describeLastUpdateTime(RpcContext context, DescribeLastUpdateTimeRequest request);

    /**
     * DeleteCustomText
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DeleteCustomTextResponse}
     */
    @TRpcMethod(name = "DeleteCustomText")
    CompletionStage<DeleteCustomTextResponse> deleteCustomText(RpcContext context, DeleteCustomTextRequest request);

    /**
     * CreateFeature
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link CreateFeatureResponse}
     */
    @TRpcMethod(name = "CreateFeature")
    CompletionStage<CreateFeatureResponse> createFeature(RpcContext context, CreateFeatureRequest request);

    /**
     * ModifyFeature
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link ModifyFeatureResponse}
     */
    @TRpcMethod(name = "ModifyFeature")
    CompletionStage<ModifyFeatureResponse> modifyFeature(RpcContext context, ModifyFeatureRequest request);

    /**
     * DescribeFeatures
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeFeaturesResponse}
     */
    @TRpcMethod(name = "DescribeFeatures")
    CompletionStage<DescribeFeaturesResponse> describeFeatures(RpcContext context, DescribeFeaturesRequest request);

    /**
     * DeleteFeature
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DeleteFeatureResponse}
     */
    @TRpcMethod(name = "DeleteFeature")
    CompletionStage<DeleteFeatureResponse> deleteFeature(RpcContext context, DeleteFeatureRequest request);
}