package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.CustomFeatureProtocol.DescribeTextCategoriesRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeTextCategoriesResponse;
import com.tencent.aimedia.CustomFeatureProtocol.CreateCustomTextRequest;
import com.tencent.aimedia.CustomFeatureProtocol.CreateCustomTextResponse;
import com.tencent.aimedia.CustomFeatureProtocol.ModifyCustomTextRequest;
import com.tencent.aimedia.CustomFeatureProtocol.ModifyCustomTextResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeCustomTextsRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeCustomTextsResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeLastUpdateTimeRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeLastUpdateTimeResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DeleteCustomTextRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DeleteCustomTextResponse;
import com.tencent.aimedia.CustomFeatureProtocol.CreateFeatureRequest;
import com.tencent.aimedia.CustomFeatureProtocol.CreateFeatureResponse;
import com.tencent.aimedia.CustomFeatureProtocol.ModifyFeatureRequest;
import com.tencent.aimedia.CustomFeatureProtocol.ModifyFeatureResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeFeaturesRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DescribeFeaturesResponse;
import com.tencent.aimedia.CustomFeatureProtocol.DeleteFeatureRequest;
import com.tencent.aimedia.CustomFeatureProtocol.DeleteFeatureResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.customfeature.CustomFeature")
public interface CustomFeatureAPI {

    /**
     * DescribeTextCategories
     *
     * @param context context
     * @param request request
     * @return {@link DescribeTextCategoriesResponse}
     */
    @TRpcMethod(name = "DescribeTextCategories")
    DescribeTextCategoriesResponse describeTextCategories(RpcContext context, DescribeTextCategoriesRequest request);

    /**
     * CreateCustomText
     *
     * @param context context
     * @param request request
     * @return {@link CreateCustomTextResponse}
     */
    @TRpcMethod(name = "CreateCustomText")
    CreateCustomTextResponse createCustomText(RpcContext context, CreateCustomTextRequest request);

    /**
     * ModifyCustomText
     *
     * @param context context
     * @param request request
     * @return {@link ModifyCustomTextResponse}
     */
    @TRpcMethod(name = "ModifyCustomText")
    ModifyCustomTextResponse modifyCustomText(RpcContext context, ModifyCustomTextRequest request);

    /**
     * DescribeCustomTexts
     *
     * @param context context
     * @param request request
     * @return {@link DescribeCustomTextsResponse}
     */
    @TRpcMethod(name = "DescribeCustomTexts")
    DescribeCustomTextsResponse describeCustomTexts(RpcContext context, DescribeCustomTextsRequest request);

    /**
     * DescribeLastUpdateTime
     *
     * @param context context
     * @param request request
     * @return {@link DescribeLastUpdateTimeResponse}
     */
    @TRpcMethod(name = "DescribeLastUpdateTime")
    DescribeLastUpdateTimeResponse describeLastUpdateTime(RpcContext context, DescribeLastUpdateTimeRequest request);

    /**
     * DeleteCustomText
     *
     * @param context context
     * @param request request
     * @return {@link DeleteCustomTextResponse}
     */
    @TRpcMethod(name = "DeleteCustomText")
    DeleteCustomTextResponse deleteCustomText(RpcContext context, DeleteCustomTextRequest request);

    /**
     * CreateFeature
     *
     * @param context context
     * @param request request
     * @return {@link CreateFeatureResponse}
     */
    @TRpcMethod(name = "CreateFeature")
    CreateFeatureResponse createFeature(RpcContext context, CreateFeatureRequest request);

    /**
     * ModifyFeature
     *
     * @param context context
     * @param request request
     * @return {@link ModifyFeatureResponse}
     */
    @TRpcMethod(name = "ModifyFeature")
    ModifyFeatureResponse modifyFeature(RpcContext context, ModifyFeatureRequest request);

    /**
     * DescribeFeatures
     *
     * @param context context
     * @param request request
     * @return {@link DescribeFeaturesResponse}
     */
    @TRpcMethod(name = "DescribeFeatures")
    DescribeFeaturesResponse describeFeatures(RpcContext context, DescribeFeaturesRequest request);

    /**
     * DeleteFeature
     *
     * @param context context
     * @param request request
     * @return {@link DeleteFeatureResponse}
     */
    @TRpcMethod(name = "DeleteFeature")
    DeleteFeatureResponse deleteFeature(RpcContext context, DeleteFeatureRequest request);
}