package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.MediaProtocol.CreateMediasRequest;
import com.tencent.aimedia.MediaProtocol.CreateMediasResponse;
import com.tencent.aimedia.MediaProtocol.CommitMediasRequest;
import com.tencent.aimedia.MediaProtocol.CommitMediasResponse;
import com.tencent.aimedia.MediaProtocol.DescribeMediasRequest;
import com.tencent.aimedia.MediaProtocol.DescribeMediasResponse;
import com.tencent.aimedia.MediaProtocol.DescribeMediaDetailsRequest;
import com.tencent.aimedia.MediaProtocol.DescribeMediaDetailsResponse;
import com.tencent.aimedia.MediaProtocol.DeleteMediasRequest;
import com.tencent.aimedia.MediaProtocol.DeleteMediasResponse;
import com.tencent.aimedia.MediaProtocol.RestoreDeletedMediasRequest;
import com.tencent.aimedia.MediaProtocol.RestoreDeletedMediasResponse;
import com.tencent.aimedia.MediaProtocol.EmptyTrashRequest;
import com.tencent.aimedia.MediaProtocol.EmptyTrashResponse;
import com.tencent.aimedia.MediaProtocol.DescribeCategoriesRequest;
import com.tencent.aimedia.MediaProtocol.DescribeCategoriesResponse;
import com.tencent.aimedia.MediaProtocol.ModifyMediaRequest;
import com.tencent.aimedia.MediaProtocol.ModifyMediaResponse;
import com.tencent.aimedia.MediaProtocol.RetrieveRelevantTagsRequest;
import com.tencent.aimedia.MediaProtocol.RetrieveRelevantTagsResponse;
import com.tencent.aimedia.MediaProtocol.RetrieveLexicalEntryRequest;
import com.tencent.aimedia.MediaProtocol.RetrieveLexicalEntryResponse;
import com.tencent.aimedia.MediaProtocol.RetrieveMediasRequest;
import com.tencent.aimedia.MediaProtocol.RetrieveMediasResponse;
import com.tencent.aimedia.MediaProtocol.RetrieveFacesResponse;
import com.tencent.aimedia.MediaProtocol.RetrieveConsistentMediasRequest;
import com.tencent.aimedia.MediaProtocol.RetrieveConsistentMediasResponse;
import com.tencent.aimedia.MediaProtocol.AssociateWordsRequest;
import com.tencent.aimedia.MediaProtocol.AssociateWordsResponse;
import com.tencent.aimedia.MediaProtocol.ExtractImagesRequest;
import com.tencent.aimedia.MediaProtocol.ExtractImagesResponse;
import com.tencent.aimedia.MediaProtocol.CreateResourcePackageRequest;
import com.tencent.aimedia.MediaProtocol.CreateResourcePackageResponse;
import com.tencent.aimedia.MediaProtocol.DeleteResourcePackageRequest;
import com.tencent.aimedia.MediaProtocol.ResourcePackageOperateResponse;
import com.tencent.aimedia.MediaProtocol.UpdateResourcePackageRequest;
import com.tencent.aimedia.MediaProtocol.DescribeResourcePackageRequest;
import com.tencent.aimedia.MediaProtocol.DescribePackageResponse;
import com.tencent.aimedia.MediaProtocol.AddResourceToPackageRequest;
import com.tencent.aimedia.MediaProtocol.AddResourceToPackageResponse;
import com.tencent.aimedia.MediaProtocol.DeleteResourceFromPackageRequest;
import com.tencent.aimedia.MediaProtocol.UndeleteResourceFromPackageRequest;
import com.tencent.aimedia.MediaProtocol.BindMediasRequest;
import com.tencent.aimedia.MediaProtocol.BindMediasResponse;
import com.tencent.aimedia.MediaProtocol.DescribeMediaDetailsInnerRequest;
import com.tencent.aimedia.MediaProtocol.DescribeMediaDetailsInnerResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.media.Media")
public interface MediaAPI {

    /**
     * CreateMedias
     *
     * @param context context
     * @param request request
     * @return {@link CreateMediasResponse}
     */
    @TRpcMethod(name = "CreateMedias")
    CreateMediasResponse createMedias(RpcContext context, CreateMediasRequest request);

    /**
     * CommitMedias
     *
     * @param context context
     * @param request request
     * @return {@link CommitMediasResponse}
     */
    @TRpcMethod(name = "CommitMedias")
    CommitMediasResponse commitMedias(RpcContext context, CommitMediasRequest request);

    /**
     * DescribeMedias
     *
     * @param context context
     * @param request request
     * @return {@link DescribeMediasResponse}
     */
    @TRpcMethod(name = "DescribeMedias")
    DescribeMediasResponse describeMedias(RpcContext context, DescribeMediasRequest request);

    /**
     * DescribeMediaDetails
     *
     * @param context context
     * @param request request
     * @return {@link DescribeMediaDetailsResponse}
     */
    @TRpcMethod(name = "DescribeMediaDetails")
    DescribeMediaDetailsResponse describeMediaDetails(RpcContext context, DescribeMediaDetailsRequest request);

    /**
     * DeleteMedias
     *
     * @param context context
     * @param request request
     * @return {@link DeleteMediasResponse}
     */
    @TRpcMethod(name = "DeleteMedias")
    DeleteMediasResponse deleteMedias(RpcContext context, DeleteMediasRequest request);

    /**
     * RestoreDeletedMedias
     *
     * @param context context
     * @param request request
     * @return {@link RestoreDeletedMediasResponse}
     */
    @TRpcMethod(name = "RestoreDeletedMedias")
    RestoreDeletedMediasResponse restoreDeletedMedias(RpcContext context, RestoreDeletedMediasRequest request);

    /**
     * EmptyTrash
     *
     * @param context context
     * @param request request
     * @return {@link EmptyTrashResponse}
     */
    @TRpcMethod(name = "EmptyTrash")
    EmptyTrashResponse emptyTrash(RpcContext context, EmptyTrashRequest request);

    /**
     * DescribeCategories
     *
     * @param context context
     * @param request request
     * @return {@link DescribeCategoriesResponse}
     */
    @TRpcMethod(name = "DescribeCategories")
    DescribeCategoriesResponse describeCategories(RpcContext context, DescribeCategoriesRequest request);

    /**
     * ModifyMedia
     *
     * @param context context
     * @param request request
     * @return {@link ModifyMediaResponse}
     */
    @TRpcMethod(name = "ModifyMedia")
    ModifyMediaResponse modifyMedia(RpcContext context, ModifyMediaRequest request);

    /**
     * RetrieveRelevantTags
     *
     * @param context context
     * @param request request
     * @return {@link RetrieveRelevantTagsResponse}
     */
    @TRpcMethod(name = "RetrieveRelevantTags")
    RetrieveRelevantTagsResponse retrieveRelevantTags(RpcContext context, RetrieveRelevantTagsRequest request);

    /**
     * RetrieveLexicalEntry
     *
     * @param context context
     * @param request request
     * @return {@link RetrieveLexicalEntryResponse}
     */
    @TRpcMethod(name = "RetrieveLexicalEntry")
    RetrieveLexicalEntryResponse retrieveLexicalEntry(RpcContext context, RetrieveLexicalEntryRequest request);

    /**
     * RetrieveTitleMedias
     *
     * @param context context
     * @param request request
     * @return {@link RetrieveMediasResponse}
     */
    @TRpcMethod(name = "RetrieveTitleMedias")
    RetrieveMediasResponse retrieveTitleMedias(RpcContext context, RetrieveMediasRequest request);

    /**
     * RetrieveContentMedias
     *
     * @param context context
     * @param request request
     * @return {@link RetrieveMediasResponse}
     */
    @TRpcMethod(name = "RetrieveContentMedias")
    RetrieveMediasResponse retrieveContentMedias(RpcContext context, RetrieveMediasRequest request);

    /**
     * RetrieveTextMultiModalMedias
     *
     * @param context context
     * @param request request
     * @return {@link RetrieveMediasResponse}
     */
    @TRpcMethod(name = "RetrieveTextMultiModalMedias")
    RetrieveMediasResponse retrieveTextMultiModalMedias(RpcContext context, RetrieveMediasRequest request);

    /**
     * RetrieveTextCrossModalMedias
     *
     * @param context context
     * @param request request
     * @return {@link RetrieveMediasResponse}
     */
    @TRpcMethod(name = "RetrieveTextCrossModalMedias")
    RetrieveMediasResponse retrieveTextCrossModalMedias(RpcContext context, RetrieveMediasRequest request);

    /**
     * RetrieveSimilarMedias
     *
     * @param context context
     * @param request request
     * @return {@link RetrieveMediasResponse}
     */
    @TRpcMethod(name = "RetrieveSimilarMedias")
    RetrieveMediasResponse retrieveSimilarMedias(RpcContext context, RetrieveMediasRequest request);

    /**
     * RetrieveFaces
     *
     * @param context context
     * @param request request
     * @return {@link RetrieveFacesResponse}
     */
    @TRpcMethod(name = "RetrieveFaces")
    RetrieveFacesResponse retrieveFaces(RpcContext context, RetrieveMediasRequest request);

    /**
     * RetrieveConsistentMedias
     *
     * @param context context
     * @param request request
     * @return {@link RetrieveConsistentMediasResponse}
     */
    @TRpcMethod(name = "RetrieveConsistentMedias")
    RetrieveConsistentMediasResponse retrieveConsistentMedias(RpcContext context, RetrieveConsistentMediasRequest request);

    /**
     * AssociateWords
     *
     * @param context context
     * @param request request
     * @return {@link AssociateWordsResponse}
     */
    @TRpcMethod(name = "AssociateWords")
    AssociateWordsResponse associateWords(RpcContext context, AssociateWordsRequest request);

    /**
     * ExtractImages
     *
     * @param context context
     * @param request request
     * @return {@link ExtractImagesResponse}
     */
    @TRpcMethod(name = "ExtractImages")
    ExtractImagesResponse extractImages(RpcContext context, ExtractImagesRequest request);

    /**
     * CreateResourcePackage
     *
     * @param context context
     * @param request request
     * @return {@link CreateResourcePackageResponse}
     */
    @TRpcMethod(name = "CreateResourcePackage")
    CreateResourcePackageResponse createResourcePackage(RpcContext context, CreateResourcePackageRequest request);

    /**
     * DeleteResourcePackage
     *
     * @param context context
     * @param request request
     * @return {@link ResourcePackageOperateResponse}
     */
    @TRpcMethod(name = "DeleteResourcePackage")
    ResourcePackageOperateResponse deleteResourcePackage(RpcContext context, DeleteResourcePackageRequest request);

    /**
     * UpdateResourcePackage
     *
     * @param context context
     * @param request request
     * @return {@link ResourcePackageOperateResponse}
     */
    @TRpcMethod(name = "UpdateResourcePackage")
    ResourcePackageOperateResponse updateResourcePackage(RpcContext context, UpdateResourcePackageRequest request);

    /**
     * DescribeResourcePackage
     *
     * @param context context
     * @param request request
     * @return {@link DescribePackageResponse}
     */
    @TRpcMethod(name = "DescribeResourcePackage")
    DescribePackageResponse describeResourcePackage(RpcContext context, DescribeResourcePackageRequest request);

    /**
     * AddResourceToPackage
     *
     * @param context context
     * @param request request
     * @return {@link AddResourceToPackageResponse}
     */
    @TRpcMethod(name = "AddResourceToPackage")
    AddResourceToPackageResponse addResourceToPackage(RpcContext context, AddResourceToPackageRequest request);

    /**
     * DeleteResourceFromPackage
     *
     * @param context context
     * @param request request
     * @return {@link ResourcePackageOperateResponse}
     */
    @TRpcMethod(name = "DeleteResourceFromPackage")
    ResourcePackageOperateResponse deleteResourceFromPackage(RpcContext context, DeleteResourceFromPackageRequest request);

    /**
     * UndeleteResourceFromPackage
     *
     * @param context context
     * @param request request
     * @return {@link ResourcePackageOperateResponse}
     */
    @TRpcMethod(name = "UndeleteResourceFromPackage")
    ResourcePackageOperateResponse undeleteResourceFromPackage(RpcContext context, UndeleteResourceFromPackageRequest request);

    /**
     * BindMedias
     *
     * @param context context
     * @param request request
     * @return {@link BindMediasResponse}
     */
    @TRpcMethod(name = "BindMedias")
    BindMediasResponse bindMedias(RpcContext context, BindMediasRequest request);

    /**
     * DescribeMediaDetailsInner
     *
     * @param context context
     * @param request request
     * @return {@link DescribeMediaDetailsInnerResponse}
     */
    @TRpcMethod(name = "DescribeMediaDetailsInner")
    DescribeMediaDetailsInnerResponse describeMediaDetailsInner(RpcContext context, DescribeMediaDetailsInnerRequest request);
}