// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: media_crop.proto

package com.tencent.aimedia;

public final class MediaCropProtocol {
  private MediaCropProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerStorageParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trpc.media.mediacrop.CustomerStorageParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string MediaName = 1;</code>
     * @return The mediaName.
     */
    java.lang.String getMediaName();
    /**
     * <code>string MediaName = 1;</code>
     * @return The bytes for mediaName.
     */
    com.google.protobuf.ByteString
        getMediaNameBytes();

    /**
     * <code>.trpc.media.common.DomainGroupType DomainGroupType = 2;</code>
     * @return The enum numeric value on the wire for domainGroupType.
     */
    int getDomainGroupTypeValue();
    /**
     * <code>.trpc.media.common.DomainGroupType DomainGroupType = 2;</code>
     * @return The domainGroupType.
     */
    com.tencent.aimedia.CommonProtocol.DomainGroupType getDomainGroupType();
  }
  /**
   * Protobuf type {@code trpc.media.mediacrop.CustomerStorageParam}
   */
  public static final class CustomerStorageParam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trpc.media.mediacrop.CustomerStorageParam)
      CustomerStorageParamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomerStorageParam.newBuilder() to construct.
    private CustomerStorageParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomerStorageParam() {
      mediaName_ = "";
      domainGroupType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CustomerStorageParam();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CustomerStorageParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CustomerStorageParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.class, com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.Builder.class);
    }

    public static final int MEDIANAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object mediaName_;
    /**
     * <code>string MediaName = 1;</code>
     * @return The mediaName.
     */
    @java.lang.Override
    public java.lang.String getMediaName() {
      java.lang.Object ref = mediaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaName_ = s;
        return s;
      }
    }
    /**
     * <code>string MediaName = 1;</code>
     * @return The bytes for mediaName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMediaNameBytes() {
      java.lang.Object ref = mediaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOMAINGROUPTYPE_FIELD_NUMBER = 2;
    private int domainGroupType_;
    /**
     * <code>.trpc.media.common.DomainGroupType DomainGroupType = 2;</code>
     * @return The enum numeric value on the wire for domainGroupType.
     */
    @java.lang.Override public int getDomainGroupTypeValue() {
      return domainGroupType_;
    }
    /**
     * <code>.trpc.media.common.DomainGroupType DomainGroupType = 2;</code>
     * @return The domainGroupType.
     */
    @java.lang.Override public com.tencent.aimedia.CommonProtocol.DomainGroupType getDomainGroupType() {
      @SuppressWarnings("deprecation")
      com.tencent.aimedia.CommonProtocol.DomainGroupType result = com.tencent.aimedia.CommonProtocol.DomainGroupType.valueOf(domainGroupType_);
      return result == null ? com.tencent.aimedia.CommonProtocol.DomainGroupType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mediaName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mediaName_);
      }
      if (domainGroupType_ != com.tencent.aimedia.CommonProtocol.DomainGroupType.DOMAIN_GROUP_TYPE_PRIVATE.getNumber()) {
        output.writeEnum(2, domainGroupType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mediaName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mediaName_);
      }
      if (domainGroupType_ != com.tencent.aimedia.CommonProtocol.DomainGroupType.DOMAIN_GROUP_TYPE_PRIVATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, domainGroupType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam)) {
        return super.equals(obj);
      }
      com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam other = (com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam) obj;

      if (!getMediaName()
          .equals(other.getMediaName())) return false;
      if (domainGroupType_ != other.domainGroupType_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDIANAME_FIELD_NUMBER;
      hash = (53 * hash) + getMediaName().hashCode();
      hash = (37 * hash) + DOMAINGROUPTYPE_FIELD_NUMBER;
      hash = (53 * hash) + domainGroupType_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trpc.media.mediacrop.CustomerStorageParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trpc.media.mediacrop.CustomerStorageParam)
        com.tencent.aimedia.MediaCropProtocol.CustomerStorageParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CustomerStorageParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CustomerStorageParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.class, com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.Builder.class);
      }

      // Construct using com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mediaName_ = "";

        domainGroupType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CustomerStorageParam_descriptor;
      }

      @java.lang.Override
      public com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam getDefaultInstanceForType() {
        return com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam build() {
        com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam buildPartial() {
        com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam result = new com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam(this);
        result.mediaName_ = mediaName_;
        result.domainGroupType_ = domainGroupType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam) {
          return mergeFrom((com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam other) {
        if (other == com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.getDefaultInstance()) return this;
        if (!other.getMediaName().isEmpty()) {
          mediaName_ = other.mediaName_;
          onChanged();
        }
        if (other.domainGroupType_ != 0) {
          setDomainGroupTypeValue(other.getDomainGroupTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                mediaName_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 16: {
                domainGroupType_ = input.readEnum();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object mediaName_ = "";
      /**
       * <code>string MediaName = 1;</code>
       * @return The mediaName.
       */
      public java.lang.String getMediaName() {
        java.lang.Object ref = mediaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mediaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string MediaName = 1;</code>
       * @return The bytes for mediaName.
       */
      public com.google.protobuf.ByteString
          getMediaNameBytes() {
        java.lang.Object ref = mediaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mediaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MediaName = 1;</code>
       * @param value The mediaName to set.
       * @return This builder for chaining.
       */
      public Builder setMediaName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mediaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MediaName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaName() {
        
        mediaName_ = getDefaultInstance().getMediaName();
        onChanged();
        return this;
      }
      /**
       * <code>string MediaName = 1;</code>
       * @param value The bytes for mediaName to set.
       * @return This builder for chaining.
       */
      public Builder setMediaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mediaName_ = value;
        onChanged();
        return this;
      }

      private int domainGroupType_ = 0;
      /**
       * <code>.trpc.media.common.DomainGroupType DomainGroupType = 2;</code>
       * @return The enum numeric value on the wire for domainGroupType.
       */
      @java.lang.Override public int getDomainGroupTypeValue() {
        return domainGroupType_;
      }
      /**
       * <code>.trpc.media.common.DomainGroupType DomainGroupType = 2;</code>
       * @param value The enum numeric value on the wire for domainGroupType to set.
       * @return This builder for chaining.
       */
      public Builder setDomainGroupTypeValue(int value) {
        
        domainGroupType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.trpc.media.common.DomainGroupType DomainGroupType = 2;</code>
       * @return The domainGroupType.
       */
      @java.lang.Override
      public com.tencent.aimedia.CommonProtocol.DomainGroupType getDomainGroupType() {
        @SuppressWarnings("deprecation")
        com.tencent.aimedia.CommonProtocol.DomainGroupType result = com.tencent.aimedia.CommonProtocol.DomainGroupType.valueOf(domainGroupType_);
        return result == null ? com.tencent.aimedia.CommonProtocol.DomainGroupType.UNRECOGNIZED : result;
      }
      /**
       * <code>.trpc.media.common.DomainGroupType DomainGroupType = 2;</code>
       * @param value The domainGroupType to set.
       * @return This builder for chaining.
       */
      public Builder setDomainGroupType(com.tencent.aimedia.CommonProtocol.DomainGroupType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        domainGroupType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.trpc.media.common.DomainGroupType DomainGroupType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDomainGroupType() {
        
        domainGroupType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trpc.media.mediacrop.CustomerStorageParam)
    }

    // @@protoc_insertion_point(class_scope:trpc.media.mediacrop.CustomerStorageParam)
    private static final com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam();
    }

    public static com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomerStorageParam>
        PARSER = new com.google.protobuf.AbstractParser<CustomerStorageParam>() {
      @java.lang.Override
      public CustomerStorageParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CustomerStorageParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerStorageParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CropConversionParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trpc.media.mediacrop.CropConversionParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string StartTime = 1;</code>
     * @return The startTime.
     */
    java.lang.String getStartTime();
    /**
     * <code>string StartTime = 1;</code>
     * @return The bytes for startTime.
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    /**
     * <code>string EndTime = 2;</code>
     * @return The endTime.
     */
    java.lang.String getEndTime();
    /**
     * <code>string EndTime = 2;</code>
     * @return The bytes for endTime.
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();

    /**
     * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
     * @return Whether the customerStorageParam field is set.
     */
    boolean hasCustomerStorageParam();
    /**
     * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
     * @return The customerStorageParam.
     */
    com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam getCustomerStorageParam();
    /**
     * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
     */
    com.tencent.aimedia.MediaCropProtocol.CustomerStorageParamOrBuilder getCustomerStorageParamOrBuilder();
  }
  /**
   * Protobuf type {@code trpc.media.mediacrop.CropConversionParam}
   */
  public static final class CropConversionParam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trpc.media.mediacrop.CropConversionParam)
      CropConversionParamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CropConversionParam.newBuilder() to construct.
    private CropConversionParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CropConversionParam() {
      startTime_ = "";
      endTime_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CropConversionParam();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CropConversionParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CropConversionParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.aimedia.MediaCropProtocol.CropConversionParam.class, com.tencent.aimedia.MediaCropProtocol.CropConversionParam.Builder.class);
    }

    public static final int STARTTIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object startTime_;
    /**
     * <code>string StartTime = 1;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      }
    }
    /**
     * <code>string StartTime = 1;</code>
     * @return The bytes for startTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDTIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object endTime_;
    /**
     * <code>string EndTime = 2;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      }
    }
    /**
     * <code>string EndTime = 2;</code>
     * @return The bytes for endTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMERSTORAGEPARAM_FIELD_NUMBER = 3;
    private com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam customerStorageParam_;
    /**
     * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
     * @return Whether the customerStorageParam field is set.
     */
    @java.lang.Override
    public boolean hasCustomerStorageParam() {
      return customerStorageParam_ != null;
    }
    /**
     * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
     * @return The customerStorageParam.
     */
    @java.lang.Override
    public com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam getCustomerStorageParam() {
      return customerStorageParam_ == null ? com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.getDefaultInstance() : customerStorageParam_;
    }
    /**
     * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
     */
    @java.lang.Override
    public com.tencent.aimedia.MediaCropProtocol.CustomerStorageParamOrBuilder getCustomerStorageParamOrBuilder() {
      return getCustomerStorageParam();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTime_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, startTime_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTime_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, endTime_);
      }
      if (customerStorageParam_ != null) {
        output.writeMessage(3, getCustomerStorageParam());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTime_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, startTime_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTime_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, endTime_);
      }
      if (customerStorageParam_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCustomerStorageParam());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.aimedia.MediaCropProtocol.CropConversionParam)) {
        return super.equals(obj);
      }
      com.tencent.aimedia.MediaCropProtocol.CropConversionParam other = (com.tencent.aimedia.MediaCropProtocol.CropConversionParam) obj;

      if (!getStartTime()
          .equals(other.getStartTime())) return false;
      if (!getEndTime()
          .equals(other.getEndTime())) return false;
      if (hasCustomerStorageParam() != other.hasCustomerStorageParam()) return false;
      if (hasCustomerStorageParam()) {
        if (!getCustomerStorageParam()
            .equals(other.getCustomerStorageParam())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getEndTime().hashCode();
      if (hasCustomerStorageParam()) {
        hash = (37 * hash) + CUSTOMERSTORAGEPARAM_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerStorageParam().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.aimedia.MediaCropProtocol.CropConversionParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trpc.media.mediacrop.CropConversionParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trpc.media.mediacrop.CropConversionParam)
        com.tencent.aimedia.MediaCropProtocol.CropConversionParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CropConversionParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CropConversionParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.aimedia.MediaCropProtocol.CropConversionParam.class, com.tencent.aimedia.MediaCropProtocol.CropConversionParam.Builder.class);
      }

      // Construct using com.tencent.aimedia.MediaCropProtocol.CropConversionParam.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        startTime_ = "";

        endTime_ = "";

        if (customerStorageParamBuilder_ == null) {
          customerStorageParam_ = null;
        } else {
          customerStorageParam_ = null;
          customerStorageParamBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.aimedia.MediaCropProtocol.internal_static_trpc_media_mediacrop_CropConversionParam_descriptor;
      }

      @java.lang.Override
      public com.tencent.aimedia.MediaCropProtocol.CropConversionParam getDefaultInstanceForType() {
        return com.tencent.aimedia.MediaCropProtocol.CropConversionParam.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.aimedia.MediaCropProtocol.CropConversionParam build() {
        com.tencent.aimedia.MediaCropProtocol.CropConversionParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.aimedia.MediaCropProtocol.CropConversionParam buildPartial() {
        com.tencent.aimedia.MediaCropProtocol.CropConversionParam result = new com.tencent.aimedia.MediaCropProtocol.CropConversionParam(this);
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        if (customerStorageParamBuilder_ == null) {
          result.customerStorageParam_ = customerStorageParam_;
        } else {
          result.customerStorageParam_ = customerStorageParamBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.aimedia.MediaCropProtocol.CropConversionParam) {
          return mergeFrom((com.tencent.aimedia.MediaCropProtocol.CropConversionParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.aimedia.MediaCropProtocol.CropConversionParam other) {
        if (other == com.tencent.aimedia.MediaCropProtocol.CropConversionParam.getDefaultInstance()) return this;
        if (!other.getStartTime().isEmpty()) {
          startTime_ = other.startTime_;
          onChanged();
        }
        if (!other.getEndTime().isEmpty()) {
          endTime_ = other.endTime_;
          onChanged();
        }
        if (other.hasCustomerStorageParam()) {
          mergeCustomerStorageParam(other.getCustomerStorageParam());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                startTime_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                endTime_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getCustomerStorageParamFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object startTime_ = "";
      /**
       * <code>string StartTime = 1;</code>
       * @return The startTime.
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string StartTime = 1;</code>
       * @return The bytes for startTime.
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string StartTime = 1;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string StartTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>string StartTime = 1;</code>
       * @param value The bytes for startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endTime_ = "";
      /**
       * <code>string EndTime = 2;</code>
       * @return The endTime.
       */
      public java.lang.String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string EndTime = 2;</code>
       * @return The bytes for endTime.
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        java.lang.Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string EndTime = 2;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string EndTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <code>string EndTime = 2;</code>
       * @param value The bytes for endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endTime_ = value;
        onChanged();
        return this;
      }

      private com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam customerStorageParam_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam, com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.Builder, com.tencent.aimedia.MediaCropProtocol.CustomerStorageParamOrBuilder> customerStorageParamBuilder_;
      /**
       * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
       * @return Whether the customerStorageParam field is set.
       */
      public boolean hasCustomerStorageParam() {
        return customerStorageParamBuilder_ != null || customerStorageParam_ != null;
      }
      /**
       * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
       * @return The customerStorageParam.
       */
      public com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam getCustomerStorageParam() {
        if (customerStorageParamBuilder_ == null) {
          return customerStorageParam_ == null ? com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.getDefaultInstance() : customerStorageParam_;
        } else {
          return customerStorageParamBuilder_.getMessage();
        }
      }
      /**
       * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
       */
      public Builder setCustomerStorageParam(com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam value) {
        if (customerStorageParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          customerStorageParam_ = value;
          onChanged();
        } else {
          customerStorageParamBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
       */
      public Builder setCustomerStorageParam(
          com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.Builder builderForValue) {
        if (customerStorageParamBuilder_ == null) {
          customerStorageParam_ = builderForValue.build();
          onChanged();
        } else {
          customerStorageParamBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
       */
      public Builder mergeCustomerStorageParam(com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam value) {
        if (customerStorageParamBuilder_ == null) {
          if (customerStorageParam_ != null) {
            customerStorageParam_ =
              com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.newBuilder(customerStorageParam_).mergeFrom(value).buildPartial();
          } else {
            customerStorageParam_ = value;
          }
          onChanged();
        } else {
          customerStorageParamBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
       */
      public Builder clearCustomerStorageParam() {
        if (customerStorageParamBuilder_ == null) {
          customerStorageParam_ = null;
          onChanged();
        } else {
          customerStorageParam_ = null;
          customerStorageParamBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
       */
      public com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.Builder getCustomerStorageParamBuilder() {
        
        onChanged();
        return getCustomerStorageParamFieldBuilder().getBuilder();
      }
      /**
       * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
       */
      public com.tencent.aimedia.MediaCropProtocol.CustomerStorageParamOrBuilder getCustomerStorageParamOrBuilder() {
        if (customerStorageParamBuilder_ != null) {
          return customerStorageParamBuilder_.getMessageOrBuilder();
        } else {
          return customerStorageParam_ == null ?
              com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.getDefaultInstance() : customerStorageParam_;
        }
      }
      /**
       * <code>.trpc.media.mediacrop.CustomerStorageParam CustomerStorageParam = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam, com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.Builder, com.tencent.aimedia.MediaCropProtocol.CustomerStorageParamOrBuilder> 
          getCustomerStorageParamFieldBuilder() {
        if (customerStorageParamBuilder_ == null) {
          customerStorageParamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam, com.tencent.aimedia.MediaCropProtocol.CustomerStorageParam.Builder, com.tencent.aimedia.MediaCropProtocol.CustomerStorageParamOrBuilder>(
                  getCustomerStorageParam(),
                  getParentForChildren(),
                  isClean());
          customerStorageParam_ = null;
        }
        return customerStorageParamBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trpc.media.mediacrop.CropConversionParam)
    }

    // @@protoc_insertion_point(class_scope:trpc.media.mediacrop.CropConversionParam)
    private static final com.tencent.aimedia.MediaCropProtocol.CropConversionParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.aimedia.MediaCropProtocol.CropConversionParam();
    }

    public static com.tencent.aimedia.MediaCropProtocol.CropConversionParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CropConversionParam>
        PARSER = new com.google.protobuf.AbstractParser<CropConversionParam>() {
      @java.lang.Override
      public CropConversionParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CropConversionParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CropConversionParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.aimedia.MediaCropProtocol.CropConversionParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trpc_media_mediacrop_CustomerStorageParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trpc_media_mediacrop_CustomerStorageParam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trpc_media_mediacrop_CropConversionParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trpc_media_mediacrop_CropConversionParam_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020media_crop.proto\022\024trpc.media.mediacrop" +
      "\032\014common.proto\"f\n\024CustomerStorageParam\022\021" +
      "\n\tMediaName\030\001 \001(\t\022;\n\017DomainGroupType\030\002 \001" +
      "(\0162\".trpc.media.common.DomainGroupType\"\203" +
      "\001\n\023CropConversionParam\022\021\n\tStartTime\030\001 \001(" +
      "\t\022\017\n\007EndTime\030\002 \001(\t\022H\n\024CustomerStoragePar" +
      "am\030\003 \001(\0132*.trpc.media.mediacrop.Customer" +
      "StorageParamB\220\001\n\023com.tencent.aimediaB\021Me" +
      "diaCropProtocolZfgit.code.oa.com/yt-medi" +
      "a-ai-videounderstanding/yt-ai-media-midd" +
      "le-platform-api/protobuf-spec/mediacropb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.aimedia.CommonProtocol.getDescriptor(),
        });
    internal_static_trpc_media_mediacrop_CustomerStorageParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trpc_media_mediacrop_CustomerStorageParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trpc_media_mediacrop_CustomerStorageParam_descriptor,
        new java.lang.String[] { "MediaName", "DomainGroupType", });
    internal_static_trpc_media_mediacrop_CropConversionParam_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trpc_media_mediacrop_CropConversionParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trpc_media_mediacrop_CropConversionParam_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "CustomerStorageParam", });
    com.tencent.aimedia.CommonProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
