package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.PersonretrievalProtocol.CreatePersonRetrievalTaskRequest;
import com.tencent.aimedia.PersonretrievalProtocol.CreatePersonRetrievalTaskResponse;
import com.tencent.aimedia.PersonretrievalProtocol.DescribePersonRetrievalTaskDataRequest;
import com.tencent.aimedia.PersonretrievalProtocol.DescribePersonRetrievalTaskDataResponse;
import com.tencent.aimedia.PersonretrievalProtocol.RetrievalImageRequest;
import com.tencent.aimedia.PersonretrievalProtocol.RetrievalImageResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.personretrieval.PersonRetrieval")
public interface PersonRetrievalAPI {

    /**
     * CreatePersonRetrievalTask
     *
     * @param context context
     * @param request request
     * @return {@link CreatePersonRetrievalTaskResponse}
     */
    @TRpcMethod(name = "CreatePersonRetrievalTask")
    CreatePersonRetrievalTaskResponse createPersonRetrievalTask(RpcContext context, CreatePersonRetrievalTaskRequest request);

    /**
     * DescribePersonRetrievalTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribePersonRetrievalTaskDataResponse}
     */
    @TRpcMethod(name = "DescribePersonRetrievalTaskData")
    DescribePersonRetrievalTaskDataResponse describePersonRetrievalTaskData(RpcContext context, DescribePersonRetrievalTaskDataRequest request);

    /**
     * RetrievalImage
     *
     * @param context context
     * @param request request
     * @return {@link RetrievalImageResponse}
     */
    @TRpcMethod(name = "RetrievalImage")
    RetrievalImageResponse retrievalImage(RpcContext context, RetrievalImageRequest request);
}