package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;
import java.util.concurrent.CompletionStage;

import com.tencent.aimedia.VideoEraseProtocol.CreateRemoveCaptionTaskRequest;
import com.tencent.aimedia.VideoEraseProtocol.CreateRemoveCaptionTaskResponse;
import com.tencent.aimedia.VideoEraseProtocol.DescribeRemoveCaptionTaskDataRequest;
import com.tencent.aimedia.VideoEraseProtocol.DescribeRemoveCaptionTaskDataResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.videoerase.RemoveCaption")
public interface RemoveCaptionAsyncAPI {

    /**
     * CreateRemoveCaptionTask
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link CreateRemoveCaptionTaskResponse}
     */
    @TRpcMethod(name = "CreateRemoveCaptionTask")
    CompletionStage<CreateRemoveCaptionTaskResponse> createRemoveCaptionTask(RpcContext context, CreateRemoveCaptionTaskRequest request);

    /**
     * DescribeRemoveCaptionTaskData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeRemoveCaptionTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeRemoveCaptionTaskData")
    CompletionStage<DescribeRemoveCaptionTaskDataResponse> describeRemoveCaptionTaskData(RpcContext context, DescribeRemoveCaptionTaskDataRequest request);
}