package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.VideoEraseProtocol.CreateRemoveLogoTaskRequest;
import com.tencent.aimedia.VideoEraseProtocol.CreateRemoveLogoTaskResponse;
import com.tencent.aimedia.VideoEraseProtocol.DescribeRemoveLogoTaskDataRequest;
import com.tencent.aimedia.VideoEraseProtocol.DescribeRemoveLogoTaskDataResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.videoerase.RemoveLogo")
public interface RemoveLogoAPI {

    /**
     * CreateRemoveLogoTask
     *
     * @param context context
     * @param request request
     * @return {@link CreateRemoveLogoTaskResponse}
     */
    @TRpcMethod(name = "CreateRemoveLogoTask")
    CreateRemoveLogoTaskResponse createRemoveLogoTask(RpcContext context, CreateRemoveLogoTaskRequest request);

    /**
     * DescribeRemoveLogoTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribeRemoveLogoTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeRemoveLogoTaskData")
    DescribeRemoveLogoTaskDataResponse describeRemoveLogoTaskData(RpcContext context, DescribeRemoveLogoTaskDataRequest request);
}