package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.VideoEraseProtocol.CreateRemoveCaptionTaskRequest;
import com.tencent.aimedia.VideoEraseProtocol.CreateRemoveCaptionTaskResponse;
import com.tencent.aimedia.VideoEraseProtocol.DescribeRemoveCaptionTaskDataRequest;
import com.tencent.aimedia.VideoEraseProtocol.DescribeRemoveCaptionTaskDataResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.videoerase.RemoveCaption")
public interface RemoveCaptionAPI {

    /**
     * CreateRemoveCaptionTask
     *
     * @param context context
     * @param request request
     * @return {@link CreateRemoveCaptionTaskResponse}
     */
    @TRpcMethod(name = "CreateRemoveCaptionTask")
    CreateRemoveCaptionTaskResponse createRemoveCaptionTask(RpcContext context, CreateRemoveCaptionTaskRequest request);

    /**
     * DescribeRemoveCaptionTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribeRemoveCaptionTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeRemoveCaptionTaskData")
    DescribeRemoveCaptionTaskDataResponse describeRemoveCaptionTaskData(RpcContext context, DescribeRemoveCaptionTaskDataRequest request);
}