// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shot_match.proto

package com.tencent.aimedia;

public final class ShotmatchProtocol {
  private ShotmatchProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ShotMatchInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trpc.media.shotmatch.ShotMatchInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float ScoreSet = 1;</code>
     * @return A list containing the scoreSet.
     */
    java.util.List<java.lang.Float> getScoreSetList();
    /**
     * <code>repeated float ScoreSet = 1;</code>
     * @return The count of scoreSet.
     */
    int getScoreSetCount();
    /**
     * <code>repeated float ScoreSet = 1;</code>
     * @param index The index of the element to return.
     * @return The scoreSet at the given index.
     */
    float getScoreSet(int index);
  }
  /**
   * Protobuf type {@code trpc.media.shotmatch.ShotMatchInfo}
   */
  public static final class ShotMatchInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trpc.media.shotmatch.ShotMatchInfo)
      ShotMatchInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShotMatchInfo.newBuilder() to construct.
    private ShotMatchInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShotMatchInfo() {
      scoreSet_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShotMatchInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.class, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder.class);
    }

    public static final int SCORESET_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.FloatList scoreSet_;
    /**
     * <code>repeated float ScoreSet = 1;</code>
     * @return A list containing the scoreSet.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getScoreSetList() {
      return scoreSet_;
    }
    /**
     * <code>repeated float ScoreSet = 1;</code>
     * @return The count of scoreSet.
     */
    public int getScoreSetCount() {
      return scoreSet_.size();
    }
    /**
     * <code>repeated float ScoreSet = 1;</code>
     * @param index The index of the element to return.
     * @return The scoreSet at the given index.
     */
    public float getScoreSet(int index) {
      return scoreSet_.getFloat(index);
    }
    private int scoreSetMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getScoreSetList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(scoreSetMemoizedSerializedSize);
      }
      for (int i = 0; i < scoreSet_.size(); i++) {
        output.writeFloatNoTag(scoreSet_.getFloat(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getScoreSetList().size();
        size += dataSize;
        if (!getScoreSetList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        scoreSetMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo)) {
        return super.equals(obj);
      }
      com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo other = (com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo) obj;

      if (!getScoreSetList()
          .equals(other.getScoreSetList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getScoreSetCount() > 0) {
        hash = (37 * hash) + SCORESET_FIELD_NUMBER;
        hash = (53 * hash) + getScoreSetList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trpc.media.shotmatch.ShotMatchInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trpc.media.shotmatch.ShotMatchInfo)
        com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.class, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder.class);
      }

      // Construct using com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        scoreSet_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchInfo_descriptor;
      }

      @java.lang.Override
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo getDefaultInstanceForType() {
        return com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo build() {
        com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo buildPartial() {
        com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo result = new com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          scoreSet_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.scoreSet_ = scoreSet_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo) {
          return mergeFrom((com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo other) {
        if (other == com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.getDefaultInstance()) return this;
        if (!other.scoreSet_.isEmpty()) {
          if (scoreSet_.isEmpty()) {
            scoreSet_ = other.scoreSet_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScoreSetIsMutable();
            scoreSet_.addAll(other.scoreSet_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                float v = input.readFloat();
                ensureScoreSetIsMutable();
                scoreSet_.addFloat(v);
                break;
              } // case 13
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureScoreSetIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  scoreSet_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList scoreSet_ = emptyFloatList();
      private void ensureScoreSetIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          scoreSet_ = mutableCopy(scoreSet_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float ScoreSet = 1;</code>
       * @return A list containing the scoreSet.
       */
      public java.util.List<java.lang.Float>
          getScoreSetList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(scoreSet_) : scoreSet_;
      }
      /**
       * <code>repeated float ScoreSet = 1;</code>
       * @return The count of scoreSet.
       */
      public int getScoreSetCount() {
        return scoreSet_.size();
      }
      /**
       * <code>repeated float ScoreSet = 1;</code>
       * @param index The index of the element to return.
       * @return The scoreSet at the given index.
       */
      public float getScoreSet(int index) {
        return scoreSet_.getFloat(index);
      }
      /**
       * <code>repeated float ScoreSet = 1;</code>
       * @param index The index to set the value at.
       * @param value The scoreSet to set.
       * @return This builder for chaining.
       */
      public Builder setScoreSet(
          int index, float value) {
        ensureScoreSetIsMutable();
        scoreSet_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float ScoreSet = 1;</code>
       * @param value The scoreSet to add.
       * @return This builder for chaining.
       */
      public Builder addScoreSet(float value) {
        ensureScoreSetIsMutable();
        scoreSet_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float ScoreSet = 1;</code>
       * @param values The scoreSet to add.
       * @return This builder for chaining.
       */
      public Builder addAllScoreSet(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureScoreSetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scoreSet_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float ScoreSet = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearScoreSet() {
        scoreSet_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trpc.media.shotmatch.ShotMatchInfo)
    }

    // @@protoc_insertion_point(class_scope:trpc.media.shotmatch.ShotMatchInfo)
    private static final com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo();
    }

    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShotMatchInfo>
        PARSER = new com.google.protobuf.AbstractParser<ShotMatchInfo>() {
      @java.lang.Override
      public ShotMatchInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ShotMatchInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShotMatchInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShotMatchTaskDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trpc.media.shotmatch.ShotMatchTaskData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    java.util.List<com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo> 
        getMatchSetList();
    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo getMatchSet(int index);
    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    int getMatchSetCount();
    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    java.util.List<? extends com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder> 
        getMatchSetOrBuilderList();
    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder getMatchSetOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code trpc.media.shotmatch.ShotMatchTaskData}
   */
  public static final class ShotMatchTaskData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trpc.media.shotmatch.ShotMatchTaskData)
      ShotMatchTaskDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShotMatchTaskData.newBuilder() to construct.
    private ShotMatchTaskData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShotMatchTaskData() {
      matchSet_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShotMatchTaskData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchTaskData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchTaskData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData.class, com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData.Builder.class);
    }

    public static final int MATCHSET_FIELD_NUMBER = 1;
    private java.util.List<com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo> matchSet_;
    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo> getMatchSetList() {
      return matchSet_;
    }
    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder> 
        getMatchSetOrBuilderList() {
      return matchSet_;
    }
    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    @java.lang.Override
    public int getMatchSetCount() {
      return matchSet_.size();
    }
    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    @java.lang.Override
    public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo getMatchSet(int index) {
      return matchSet_.get(index);
    }
    /**
     * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
     */
    @java.lang.Override
    public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder getMatchSetOrBuilder(
        int index) {
      return matchSet_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < matchSet_.size(); i++) {
        output.writeMessage(1, matchSet_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < matchSet_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, matchSet_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData)) {
        return super.equals(obj);
      }
      com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData other = (com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData) obj;

      if (!getMatchSetList()
          .equals(other.getMatchSetList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMatchSetCount() > 0) {
        hash = (37 * hash) + MATCHSET_FIELD_NUMBER;
        hash = (53 * hash) + getMatchSetList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trpc.media.shotmatch.ShotMatchTaskData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trpc.media.shotmatch.ShotMatchTaskData)
        com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchTaskData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchTaskData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData.class, com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData.Builder.class);
      }

      // Construct using com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (matchSetBuilder_ == null) {
          matchSet_ = java.util.Collections.emptyList();
        } else {
          matchSet_ = null;
          matchSetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.aimedia.ShotmatchProtocol.internal_static_trpc_media_shotmatch_ShotMatchTaskData_descriptor;
      }

      @java.lang.Override
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData getDefaultInstanceForType() {
        return com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData build() {
        com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData buildPartial() {
        com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData result = new com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData(this);
        int from_bitField0_ = bitField0_;
        if (matchSetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            matchSet_ = java.util.Collections.unmodifiableList(matchSet_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.matchSet_ = matchSet_;
        } else {
          result.matchSet_ = matchSetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData) {
          return mergeFrom((com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData other) {
        if (other == com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData.getDefaultInstance()) return this;
        if (matchSetBuilder_ == null) {
          if (!other.matchSet_.isEmpty()) {
            if (matchSet_.isEmpty()) {
              matchSet_ = other.matchSet_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMatchSetIsMutable();
              matchSet_.addAll(other.matchSet_);
            }
            onChanged();
          }
        } else {
          if (!other.matchSet_.isEmpty()) {
            if (matchSetBuilder_.isEmpty()) {
              matchSetBuilder_.dispose();
              matchSetBuilder_ = null;
              matchSet_ = other.matchSet_;
              bitField0_ = (bitField0_ & ~0x00000001);
              matchSetBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMatchSetFieldBuilder() : null;
            } else {
              matchSetBuilder_.addAllMessages(other.matchSet_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo m =
                    input.readMessage(
                        com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.parser(),
                        extensionRegistry);
                if (matchSetBuilder_ == null) {
                  ensureMatchSetIsMutable();
                  matchSet_.add(m);
                } else {
                  matchSetBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo> matchSet_ =
        java.util.Collections.emptyList();
      private void ensureMatchSetIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          matchSet_ = new java.util.ArrayList<com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo>(matchSet_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder> matchSetBuilder_;

      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public java.util.List<com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo> getMatchSetList() {
        if (matchSetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(matchSet_);
        } else {
          return matchSetBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public int getMatchSetCount() {
        if (matchSetBuilder_ == null) {
          return matchSet_.size();
        } else {
          return matchSetBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo getMatchSet(int index) {
        if (matchSetBuilder_ == null) {
          return matchSet_.get(index);
        } else {
          return matchSetBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public Builder setMatchSet(
          int index, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo value) {
        if (matchSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchSetIsMutable();
          matchSet_.set(index, value);
          onChanged();
        } else {
          matchSetBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public Builder setMatchSet(
          int index, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder builderForValue) {
        if (matchSetBuilder_ == null) {
          ensureMatchSetIsMutable();
          matchSet_.set(index, builderForValue.build());
          onChanged();
        } else {
          matchSetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public Builder addMatchSet(com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo value) {
        if (matchSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchSetIsMutable();
          matchSet_.add(value);
          onChanged();
        } else {
          matchSetBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public Builder addMatchSet(
          int index, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo value) {
        if (matchSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchSetIsMutable();
          matchSet_.add(index, value);
          onChanged();
        } else {
          matchSetBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public Builder addMatchSet(
          com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder builderForValue) {
        if (matchSetBuilder_ == null) {
          ensureMatchSetIsMutable();
          matchSet_.add(builderForValue.build());
          onChanged();
        } else {
          matchSetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public Builder addMatchSet(
          int index, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder builderForValue) {
        if (matchSetBuilder_ == null) {
          ensureMatchSetIsMutable();
          matchSet_.add(index, builderForValue.build());
          onChanged();
        } else {
          matchSetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public Builder addAllMatchSet(
          java.lang.Iterable<? extends com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo> values) {
        if (matchSetBuilder_ == null) {
          ensureMatchSetIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, matchSet_);
          onChanged();
        } else {
          matchSetBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public Builder clearMatchSet() {
        if (matchSetBuilder_ == null) {
          matchSet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          matchSetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public Builder removeMatchSet(int index) {
        if (matchSetBuilder_ == null) {
          ensureMatchSetIsMutable();
          matchSet_.remove(index);
          onChanged();
        } else {
          matchSetBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder getMatchSetBuilder(
          int index) {
        return getMatchSetFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder getMatchSetOrBuilder(
          int index) {
        if (matchSetBuilder_ == null) {
          return matchSet_.get(index);  } else {
          return matchSetBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public java.util.List<? extends com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder> 
           getMatchSetOrBuilderList() {
        if (matchSetBuilder_ != null) {
          return matchSetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(matchSet_);
        }
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder addMatchSetBuilder() {
        return getMatchSetFieldBuilder().addBuilder(
            com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder addMatchSetBuilder(
          int index) {
        return getMatchSetFieldBuilder().addBuilder(
            index, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .trpc.media.shotmatch.ShotMatchInfo MatchSet = 1;</code>
       */
      public java.util.List<com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder> 
           getMatchSetBuilderList() {
        return getMatchSetFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder> 
          getMatchSetFieldBuilder() {
        if (matchSetBuilder_ == null) {
          matchSetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfo.Builder, com.tencent.aimedia.ShotmatchProtocol.ShotMatchInfoOrBuilder>(
                  matchSet_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          matchSet_ = null;
        }
        return matchSetBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trpc.media.shotmatch.ShotMatchTaskData)
    }

    // @@protoc_insertion_point(class_scope:trpc.media.shotmatch.ShotMatchTaskData)
    private static final com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData();
    }

    public static com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShotMatchTaskData>
        PARSER = new com.google.protobuf.AbstractParser<ShotMatchTaskData>() {
      @java.lang.Override
      public ShotMatchTaskData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ShotMatchTaskData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShotMatchTaskData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.aimedia.ShotmatchProtocol.ShotMatchTaskData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trpc_media_shotmatch_ShotMatchInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trpc_media_shotmatch_ShotMatchInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trpc_media_shotmatch_ShotMatchTaskData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trpc_media_shotmatch_ShotMatchTaskData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020shot_match.proto\022\024trpc.media.shotmatch" +
      "\"!\n\rShotMatchInfo\022\020\n\010ScoreSet\030\001 \003(\002\"J\n\021S" +
      "hotMatchTaskData\0225\n\010MatchSet\030\001 \003(\0132#.trp" +
      "c.media.shotmatch.ShotMatchInfoB\220\001\n\023com." +
      "tencent.aimediaB\021ShotmatchProtocolZfgit." +
      "code.oa.com/yt-media-ai-videounderstandi" +
      "ng/yt-ai-media-middle-platform-api/proto" +
      "buf-spec/shotmatchb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_trpc_media_shotmatch_ShotMatchInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trpc_media_shotmatch_ShotMatchInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trpc_media_shotmatch_ShotMatchInfo_descriptor,
        new java.lang.String[] { "ScoreSet", });
    internal_static_trpc_media_shotmatch_ShotMatchTaskData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trpc_media_shotmatch_ShotMatchTaskData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trpc_media_shotmatch_ShotMatchTaskData_descriptor,
        new java.lang.String[] { "MatchSet", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
