package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.TaskProtocol.FinishedTaskRequest;
import com.tencent.aimedia.TaskProtocol.FinishedTaskResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.task.TaskCallback")
public interface TaskCallbackAPI {

    /**
     * FinishedTask
     *
     * @param context context
     * @param request request
     * @return {@link FinishedTaskResponse}
     */
    @TRpcMethod(name = "FinishedTask")
    FinishedTaskResponse finishedTask(RpcContext context, FinishedTaskRequest request);
}