// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: text_summarization.proto

package com.tencent.aimedia;

public final class TextSummarizationProtocol {
  private TextSummarizationProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SentenceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trpc.media.textsummarization.Sentence)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string Text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>repeated string Keywords = 2;</code>
     * @return A list containing the keywords.
     */
    java.util.List<java.lang.String>
        getKeywordsList();
    /**
     * <code>repeated string Keywords = 2;</code>
     * @return The count of keywords.
     */
    int getKeywordsCount();
    /**
     * <code>repeated string Keywords = 2;</code>
     * @param index The index of the element to return.
     * @return The keywords at the given index.
     */
    java.lang.String getKeywords(int index);
    /**
     * <code>repeated string Keywords = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keywords at the given index.
     */
    com.google.protobuf.ByteString
        getKeywordsBytes(int index);

    /**
     * <code>repeated float PositionPercentages = 3;</code>
     * @return A list containing the positionPercentages.
     */
    java.util.List<java.lang.Float> getPositionPercentagesList();
    /**
     * <code>repeated float PositionPercentages = 3;</code>
     * @return The count of positionPercentages.
     */
    int getPositionPercentagesCount();
    /**
     * <code>repeated float PositionPercentages = 3;</code>
     * @param index The index of the element to return.
     * @return The positionPercentages at the given index.
     */
    float getPositionPercentages(int index);
  }
  /**
   * Protobuf type {@code trpc.media.textsummarization.Sentence}
   */
  public static final class Sentence extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trpc.media.textsummarization.Sentence)
      SentenceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Sentence.newBuilder() to construct.
    private Sentence(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sentence() {
      text_ = "";
      keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      positionPercentages_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Sentence();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_Sentence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_Sentence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.aimedia.TextSummarizationProtocol.Sentence.class, com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>string Text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string Text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEYWORDS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList keywords_;
    /**
     * <code>repeated string Keywords = 2;</code>
     * @return A list containing the keywords.
     */
    public com.google.protobuf.ProtocolStringList
        getKeywordsList() {
      return keywords_;
    }
    /**
     * <code>repeated string Keywords = 2;</code>
     * @return The count of keywords.
     */
    public int getKeywordsCount() {
      return keywords_.size();
    }
    /**
     * <code>repeated string Keywords = 2;</code>
     * @param index The index of the element to return.
     * @return The keywords at the given index.
     */
    public java.lang.String getKeywords(int index) {
      return keywords_.get(index);
    }
    /**
     * <code>repeated string Keywords = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keywords at the given index.
     */
    public com.google.protobuf.ByteString
        getKeywordsBytes(int index) {
      return keywords_.getByteString(index);
    }

    public static final int POSITIONPERCENTAGES_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.FloatList positionPercentages_;
    /**
     * <code>repeated float PositionPercentages = 3;</code>
     * @return A list containing the positionPercentages.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getPositionPercentagesList() {
      return positionPercentages_;
    }
    /**
     * <code>repeated float PositionPercentages = 3;</code>
     * @return The count of positionPercentages.
     */
    public int getPositionPercentagesCount() {
      return positionPercentages_.size();
    }
    /**
     * <code>repeated float PositionPercentages = 3;</code>
     * @param index The index of the element to return.
     * @return The positionPercentages at the given index.
     */
    public float getPositionPercentages(int index) {
      return positionPercentages_.getFloat(index);
    }
    private int positionPercentagesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      for (int i = 0; i < keywords_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, keywords_.getRaw(i));
      }
      if (getPositionPercentagesList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(positionPercentagesMemoizedSerializedSize);
      }
      for (int i = 0; i < positionPercentages_.size(); i++) {
        output.writeFloatNoTag(positionPercentages_.getFloat(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < keywords_.size(); i++) {
          dataSize += computeStringSizeNoTag(keywords_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getKeywordsList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getPositionPercentagesList().size();
        size += dataSize;
        if (!getPositionPercentagesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        positionPercentagesMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.aimedia.TextSummarizationProtocol.Sentence)) {
        return super.equals(obj);
      }
      com.tencent.aimedia.TextSummarizationProtocol.Sentence other = (com.tencent.aimedia.TextSummarizationProtocol.Sentence) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (!getKeywordsList()
          .equals(other.getKeywordsList())) return false;
      if (!getPositionPercentagesList()
          .equals(other.getPositionPercentagesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      if (getKeywordsCount() > 0) {
        hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
        hash = (53 * hash) + getKeywordsList().hashCode();
      }
      if (getPositionPercentagesCount() > 0) {
        hash = (37 * hash) + POSITIONPERCENTAGES_FIELD_NUMBER;
        hash = (53 * hash) + getPositionPercentagesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.aimedia.TextSummarizationProtocol.Sentence prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trpc.media.textsummarization.Sentence}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trpc.media.textsummarization.Sentence)
        com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_Sentence_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_Sentence_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.aimedia.TextSummarizationProtocol.Sentence.class, com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder.class);
      }

      // Construct using com.tencent.aimedia.TextSummarizationProtocol.Sentence.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        text_ = "";

        keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        positionPercentages_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_Sentence_descriptor;
      }

      @java.lang.Override
      public com.tencent.aimedia.TextSummarizationProtocol.Sentence getDefaultInstanceForType() {
        return com.tencent.aimedia.TextSummarizationProtocol.Sentence.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.aimedia.TextSummarizationProtocol.Sentence build() {
        com.tencent.aimedia.TextSummarizationProtocol.Sentence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.aimedia.TextSummarizationProtocol.Sentence buildPartial() {
        com.tencent.aimedia.TextSummarizationProtocol.Sentence result = new com.tencent.aimedia.TextSummarizationProtocol.Sentence(this);
        int from_bitField0_ = bitField0_;
        result.text_ = text_;
        if (((bitField0_ & 0x00000001) != 0)) {
          keywords_ = keywords_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.keywords_ = keywords_;
        if (((bitField0_ & 0x00000002) != 0)) {
          positionPercentages_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.positionPercentages_ = positionPercentages_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.aimedia.TextSummarizationProtocol.Sentence) {
          return mergeFrom((com.tencent.aimedia.TextSummarizationProtocol.Sentence)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.aimedia.TextSummarizationProtocol.Sentence other) {
        if (other == com.tencent.aimedia.TextSummarizationProtocol.Sentence.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (!other.keywords_.isEmpty()) {
          if (keywords_.isEmpty()) {
            keywords_ = other.keywords_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKeywordsIsMutable();
            keywords_.addAll(other.keywords_);
          }
          onChanged();
        }
        if (!other.positionPercentages_.isEmpty()) {
          if (positionPercentages_.isEmpty()) {
            positionPercentages_ = other.positionPercentages_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePositionPercentagesIsMutable();
            positionPercentages_.addAll(other.positionPercentages_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                text_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureKeywordsIsMutable();
                keywords_.add(s);
                break;
              } // case 18
              case 29: {
                float v = input.readFloat();
                ensurePositionPercentagesIsMutable();
                positionPercentages_.addFloat(v);
                break;
              } // case 29
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensurePositionPercentagesIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  positionPercentages_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>string Text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string Text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureKeywordsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          keywords_ = new com.google.protobuf.LazyStringArrayList(keywords_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string Keywords = 2;</code>
       * @return A list containing the keywords.
       */
      public com.google.protobuf.ProtocolStringList
          getKeywordsList() {
        return keywords_.getUnmodifiableView();
      }
      /**
       * <code>repeated string Keywords = 2;</code>
       * @return The count of keywords.
       */
      public int getKeywordsCount() {
        return keywords_.size();
      }
      /**
       * <code>repeated string Keywords = 2;</code>
       * @param index The index of the element to return.
       * @return The keywords at the given index.
       */
      public java.lang.String getKeywords(int index) {
        return keywords_.get(index);
      }
      /**
       * <code>repeated string Keywords = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the keywords at the given index.
       */
      public com.google.protobuf.ByteString
          getKeywordsBytes(int index) {
        return keywords_.getByteString(index);
      }
      /**
       * <code>repeated string Keywords = 2;</code>
       * @param index The index to set the value at.
       * @param value The keywords to set.
       * @return This builder for chaining.
       */
      public Builder setKeywords(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordsIsMutable();
        keywords_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Keywords = 2;</code>
       * @param value The keywords to add.
       * @return This builder for chaining.
       */
      public Builder addKeywords(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordsIsMutable();
        keywords_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Keywords = 2;</code>
       * @param values The keywords to add.
       * @return This builder for chaining.
       */
      public Builder addAllKeywords(
          java.lang.Iterable<java.lang.String> values) {
        ensureKeywordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keywords_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Keywords = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeywords() {
        keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Keywords = 2;</code>
       * @param value The bytes of the keywords to add.
       * @return This builder for chaining.
       */
      public Builder addKeywordsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureKeywordsIsMutable();
        keywords_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList positionPercentages_ = emptyFloatList();
      private void ensurePositionPercentagesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          positionPercentages_ = mutableCopy(positionPercentages_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float PositionPercentages = 3;</code>
       * @return A list containing the positionPercentages.
       */
      public java.util.List<java.lang.Float>
          getPositionPercentagesList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(positionPercentages_) : positionPercentages_;
      }
      /**
       * <code>repeated float PositionPercentages = 3;</code>
       * @return The count of positionPercentages.
       */
      public int getPositionPercentagesCount() {
        return positionPercentages_.size();
      }
      /**
       * <code>repeated float PositionPercentages = 3;</code>
       * @param index The index of the element to return.
       * @return The positionPercentages at the given index.
       */
      public float getPositionPercentages(int index) {
        return positionPercentages_.getFloat(index);
      }
      /**
       * <code>repeated float PositionPercentages = 3;</code>
       * @param index The index to set the value at.
       * @param value The positionPercentages to set.
       * @return This builder for chaining.
       */
      public Builder setPositionPercentages(
          int index, float value) {
        ensurePositionPercentagesIsMutable();
        positionPercentages_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float PositionPercentages = 3;</code>
       * @param value The positionPercentages to add.
       * @return This builder for chaining.
       */
      public Builder addPositionPercentages(float value) {
        ensurePositionPercentagesIsMutable();
        positionPercentages_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float PositionPercentages = 3;</code>
       * @param values The positionPercentages to add.
       * @return This builder for chaining.
       */
      public Builder addAllPositionPercentages(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensurePositionPercentagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, positionPercentages_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float PositionPercentages = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPositionPercentages() {
        positionPercentages_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trpc.media.textsummarization.Sentence)
    }

    // @@protoc_insertion_point(class_scope:trpc.media.textsummarization.Sentence)
    private static final com.tencent.aimedia.TextSummarizationProtocol.Sentence DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.aimedia.TextSummarizationProtocol.Sentence();
    }

    public static com.tencent.aimedia.TextSummarizationProtocol.Sentence getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sentence>
        PARSER = new com.google.protobuf.AbstractParser<Sentence>() {
      @java.lang.Override
      public Sentence parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Sentence> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sentence> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.aimedia.TextSummarizationProtocol.Sentence getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TextSummarizationTaskDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trpc.media.textsummarization.TextSummarizationTaskData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Summary = 1;</code>
     * @return The summary.
     */
    java.lang.String getSummary();
    /**
     * <code>string Summary = 1;</code>
     * @return The bytes for summary.
     */
    com.google.protobuf.ByteString
        getSummaryBytes();

    /**
     * <code>string Title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string Title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    java.util.List<com.tencent.aimedia.TextSummarizationProtocol.Sentence> 
        getSentencesList();
    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    com.tencent.aimedia.TextSummarizationProtocol.Sentence getSentences(int index);
    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    int getSentencesCount();
    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    java.util.List<? extends com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder> 
        getSentencesOrBuilderList();
    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder getSentencesOrBuilder(
        int index);

    /**
     * <code>repeated string Keywords = 4;</code>
     * @return A list containing the keywords.
     */
    java.util.List<java.lang.String>
        getKeywordsList();
    /**
     * <code>repeated string Keywords = 4;</code>
     * @return The count of keywords.
     */
    int getKeywordsCount();
    /**
     * <code>repeated string Keywords = 4;</code>
     * @param index The index of the element to return.
     * @return The keywords at the given index.
     */
    java.lang.String getKeywords(int index);
    /**
     * <code>repeated string Keywords = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keywords at the given index.
     */
    com.google.protobuf.ByteString
        getKeywordsBytes(int index);
  }
  /**
   * Protobuf type {@code trpc.media.textsummarization.TextSummarizationTaskData}
   */
  public static final class TextSummarizationTaskData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trpc.media.textsummarization.TextSummarizationTaskData)
      TextSummarizationTaskDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextSummarizationTaskData.newBuilder() to construct.
    private TextSummarizationTaskData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextSummarizationTaskData() {
      summary_ = "";
      title_ = "";
      sentences_ = java.util.Collections.emptyList();
      keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TextSummarizationTaskData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_TextSummarizationTaskData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_TextSummarizationTaskData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData.class, com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData.Builder.class);
    }

    public static final int SUMMARY_FIELD_NUMBER = 1;
    private volatile java.lang.Object summary_;
    /**
     * <code>string Summary = 1;</code>
     * @return The summary.
     */
    @java.lang.Override
    public java.lang.String getSummary() {
      java.lang.Object ref = summary_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        summary_ = s;
        return s;
      }
    }
    /**
     * <code>string Summary = 1;</code>
     * @return The bytes for summary.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      java.lang.Object ref = summary_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string Title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string Title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENTENCES_FIELD_NUMBER = 3;
    private java.util.List<com.tencent.aimedia.TextSummarizationProtocol.Sentence> sentences_;
    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.tencent.aimedia.TextSummarizationProtocol.Sentence> getSentencesList() {
      return sentences_;
    }
    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder> 
        getSentencesOrBuilderList() {
      return sentences_;
    }
    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    @java.lang.Override
    public int getSentencesCount() {
      return sentences_.size();
    }
    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    @java.lang.Override
    public com.tencent.aimedia.TextSummarizationProtocol.Sentence getSentences(int index) {
      return sentences_.get(index);
    }
    /**
     * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
     */
    @java.lang.Override
    public com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder getSentencesOrBuilder(
        int index) {
      return sentences_.get(index);
    }

    public static final int KEYWORDS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList keywords_;
    /**
     * <code>repeated string Keywords = 4;</code>
     * @return A list containing the keywords.
     */
    public com.google.protobuf.ProtocolStringList
        getKeywordsList() {
      return keywords_;
    }
    /**
     * <code>repeated string Keywords = 4;</code>
     * @return The count of keywords.
     */
    public int getKeywordsCount() {
      return keywords_.size();
    }
    /**
     * <code>repeated string Keywords = 4;</code>
     * @param index The index of the element to return.
     * @return The keywords at the given index.
     */
    public java.lang.String getKeywords(int index) {
      return keywords_.get(index);
    }
    /**
     * <code>repeated string Keywords = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keywords at the given index.
     */
    public com.google.protobuf.ByteString
        getKeywordsBytes(int index) {
      return keywords_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(summary_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, summary_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      for (int i = 0; i < sentences_.size(); i++) {
        output.writeMessage(3, sentences_.get(i));
      }
      for (int i = 0; i < keywords_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, keywords_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(summary_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, summary_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      for (int i = 0; i < sentences_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, sentences_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < keywords_.size(); i++) {
          dataSize += computeStringSizeNoTag(keywords_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getKeywordsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData)) {
        return super.equals(obj);
      }
      com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData other = (com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData) obj;

      if (!getSummary()
          .equals(other.getSummary())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getSentencesList()
          .equals(other.getSentencesList())) return false;
      if (!getKeywordsList()
          .equals(other.getKeywordsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getSummary().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      if (getSentencesCount() > 0) {
        hash = (37 * hash) + SENTENCES_FIELD_NUMBER;
        hash = (53 * hash) + getSentencesList().hashCode();
      }
      if (getKeywordsCount() > 0) {
        hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
        hash = (53 * hash) + getKeywordsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trpc.media.textsummarization.TextSummarizationTaskData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trpc.media.textsummarization.TextSummarizationTaskData)
        com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_TextSummarizationTaskData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_TextSummarizationTaskData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData.class, com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData.Builder.class);
      }

      // Construct using com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        summary_ = "";

        title_ = "";

        if (sentencesBuilder_ == null) {
          sentences_ = java.util.Collections.emptyList();
        } else {
          sentences_ = null;
          sentencesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.aimedia.TextSummarizationProtocol.internal_static_trpc_media_textsummarization_TextSummarizationTaskData_descriptor;
      }

      @java.lang.Override
      public com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData getDefaultInstanceForType() {
        return com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData build() {
        com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData buildPartial() {
        com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData result = new com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData(this);
        int from_bitField0_ = bitField0_;
        result.summary_ = summary_;
        result.title_ = title_;
        if (sentencesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            sentences_ = java.util.Collections.unmodifiableList(sentences_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sentences_ = sentences_;
        } else {
          result.sentences_ = sentencesBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          keywords_ = keywords_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.keywords_ = keywords_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData) {
          return mergeFrom((com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData other) {
        if (other == com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData.getDefaultInstance()) return this;
        if (!other.getSummary().isEmpty()) {
          summary_ = other.summary_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (sentencesBuilder_ == null) {
          if (!other.sentences_.isEmpty()) {
            if (sentences_.isEmpty()) {
              sentences_ = other.sentences_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSentencesIsMutable();
              sentences_.addAll(other.sentences_);
            }
            onChanged();
          }
        } else {
          if (!other.sentences_.isEmpty()) {
            if (sentencesBuilder_.isEmpty()) {
              sentencesBuilder_.dispose();
              sentencesBuilder_ = null;
              sentences_ = other.sentences_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sentencesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSentencesFieldBuilder() : null;
            } else {
              sentencesBuilder_.addAllMessages(other.sentences_);
            }
          }
        }
        if (!other.keywords_.isEmpty()) {
          if (keywords_.isEmpty()) {
            keywords_ = other.keywords_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureKeywordsIsMutable();
            keywords_.addAll(other.keywords_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                summary_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                title_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                com.tencent.aimedia.TextSummarizationProtocol.Sentence m =
                    input.readMessage(
                        com.tencent.aimedia.TextSummarizationProtocol.Sentence.parser(),
                        extensionRegistry);
                if (sentencesBuilder_ == null) {
                  ensureSentencesIsMutable();
                  sentences_.add(m);
                } else {
                  sentencesBuilder_.addMessage(m);
                }
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureKeywordsIsMutable();
                keywords_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object summary_ = "";
      /**
       * <code>string Summary = 1;</code>
       * @return The summary.
       */
      public java.lang.String getSummary() {
        java.lang.Object ref = summary_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          summary_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Summary = 1;</code>
       * @return The bytes for summary.
       */
      public com.google.protobuf.ByteString
          getSummaryBytes() {
        java.lang.Object ref = summary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          summary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Summary = 1;</code>
       * @param value The summary to set.
       * @return This builder for chaining.
       */
      public Builder setSummary(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        summary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Summary = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSummary() {
        
        summary_ = getDefaultInstance().getSummary();
        onChanged();
        return this;
      }
      /**
       * <code>string Summary = 1;</code>
       * @param value The bytes for summary to set.
       * @return This builder for chaining.
       */
      public Builder setSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        summary_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string Title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string Title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.tencent.aimedia.TextSummarizationProtocol.Sentence> sentences_ =
        java.util.Collections.emptyList();
      private void ensureSentencesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          sentences_ = new java.util.ArrayList<com.tencent.aimedia.TextSummarizationProtocol.Sentence>(sentences_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.aimedia.TextSummarizationProtocol.Sentence, com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder, com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder> sentencesBuilder_;

      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public java.util.List<com.tencent.aimedia.TextSummarizationProtocol.Sentence> getSentencesList() {
        if (sentencesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sentences_);
        } else {
          return sentencesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public int getSentencesCount() {
        if (sentencesBuilder_ == null) {
          return sentences_.size();
        } else {
          return sentencesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public com.tencent.aimedia.TextSummarizationProtocol.Sentence getSentences(int index) {
        if (sentencesBuilder_ == null) {
          return sentences_.get(index);
        } else {
          return sentencesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public Builder setSentences(
          int index, com.tencent.aimedia.TextSummarizationProtocol.Sentence value) {
        if (sentencesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSentencesIsMutable();
          sentences_.set(index, value);
          onChanged();
        } else {
          sentencesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public Builder setSentences(
          int index, com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder builderForValue) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          sentences_.set(index, builderForValue.build());
          onChanged();
        } else {
          sentencesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public Builder addSentences(com.tencent.aimedia.TextSummarizationProtocol.Sentence value) {
        if (sentencesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSentencesIsMutable();
          sentences_.add(value);
          onChanged();
        } else {
          sentencesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public Builder addSentences(
          int index, com.tencent.aimedia.TextSummarizationProtocol.Sentence value) {
        if (sentencesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSentencesIsMutable();
          sentences_.add(index, value);
          onChanged();
        } else {
          sentencesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public Builder addSentences(
          com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder builderForValue) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          sentences_.add(builderForValue.build());
          onChanged();
        } else {
          sentencesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public Builder addSentences(
          int index, com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder builderForValue) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          sentences_.add(index, builderForValue.build());
          onChanged();
        } else {
          sentencesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public Builder addAllSentences(
          java.lang.Iterable<? extends com.tencent.aimedia.TextSummarizationProtocol.Sentence> values) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sentences_);
          onChanged();
        } else {
          sentencesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public Builder clearSentences() {
        if (sentencesBuilder_ == null) {
          sentences_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sentencesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public Builder removeSentences(int index) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          sentences_.remove(index);
          onChanged();
        } else {
          sentencesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder getSentencesBuilder(
          int index) {
        return getSentencesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder getSentencesOrBuilder(
          int index) {
        if (sentencesBuilder_ == null) {
          return sentences_.get(index);  } else {
          return sentencesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public java.util.List<? extends com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder> 
           getSentencesOrBuilderList() {
        if (sentencesBuilder_ != null) {
          return sentencesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sentences_);
        }
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder addSentencesBuilder() {
        return getSentencesFieldBuilder().addBuilder(
            com.tencent.aimedia.TextSummarizationProtocol.Sentence.getDefaultInstance());
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder addSentencesBuilder(
          int index) {
        return getSentencesFieldBuilder().addBuilder(
            index, com.tencent.aimedia.TextSummarizationProtocol.Sentence.getDefaultInstance());
      }
      /**
       * <code>repeated .trpc.media.textsummarization.Sentence Sentences = 3;</code>
       */
      public java.util.List<com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder> 
           getSentencesBuilderList() {
        return getSentencesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.aimedia.TextSummarizationProtocol.Sentence, com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder, com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder> 
          getSentencesFieldBuilder() {
        if (sentencesBuilder_ == null) {
          sentencesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tencent.aimedia.TextSummarizationProtocol.Sentence, com.tencent.aimedia.TextSummarizationProtocol.Sentence.Builder, com.tencent.aimedia.TextSummarizationProtocol.SentenceOrBuilder>(
                  sentences_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          sentences_ = null;
        }
        return sentencesBuilder_;
      }

      private com.google.protobuf.LazyStringList keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureKeywordsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          keywords_ = new com.google.protobuf.LazyStringArrayList(keywords_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string Keywords = 4;</code>
       * @return A list containing the keywords.
       */
      public com.google.protobuf.ProtocolStringList
          getKeywordsList() {
        return keywords_.getUnmodifiableView();
      }
      /**
       * <code>repeated string Keywords = 4;</code>
       * @return The count of keywords.
       */
      public int getKeywordsCount() {
        return keywords_.size();
      }
      /**
       * <code>repeated string Keywords = 4;</code>
       * @param index The index of the element to return.
       * @return The keywords at the given index.
       */
      public java.lang.String getKeywords(int index) {
        return keywords_.get(index);
      }
      /**
       * <code>repeated string Keywords = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the keywords at the given index.
       */
      public com.google.protobuf.ByteString
          getKeywordsBytes(int index) {
        return keywords_.getByteString(index);
      }
      /**
       * <code>repeated string Keywords = 4;</code>
       * @param index The index to set the value at.
       * @param value The keywords to set.
       * @return This builder for chaining.
       */
      public Builder setKeywords(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordsIsMutable();
        keywords_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Keywords = 4;</code>
       * @param value The keywords to add.
       * @return This builder for chaining.
       */
      public Builder addKeywords(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordsIsMutable();
        keywords_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Keywords = 4;</code>
       * @param values The keywords to add.
       * @return This builder for chaining.
       */
      public Builder addAllKeywords(
          java.lang.Iterable<java.lang.String> values) {
        ensureKeywordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keywords_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Keywords = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeywords() {
        keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Keywords = 4;</code>
       * @param value The bytes of the keywords to add.
       * @return This builder for chaining.
       */
      public Builder addKeywordsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureKeywordsIsMutable();
        keywords_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trpc.media.textsummarization.TextSummarizationTaskData)
    }

    // @@protoc_insertion_point(class_scope:trpc.media.textsummarization.TextSummarizationTaskData)
    private static final com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData();
    }

    public static com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextSummarizationTaskData>
        PARSER = new com.google.protobuf.AbstractParser<TextSummarizationTaskData>() {
      @java.lang.Override
      public TextSummarizationTaskData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TextSummarizationTaskData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextSummarizationTaskData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.aimedia.TextSummarizationProtocol.TextSummarizationTaskData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trpc_media_textsummarization_Sentence_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trpc_media_textsummarization_Sentence_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trpc_media_textsummarization_TextSummarizationTaskData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trpc_media_textsummarization_TextSummarizationTaskData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030text_summarization.proto\022\034trpc.media.t" +
      "extsummarization\"G\n\010Sentence\022\014\n\004Text\030\001 \001" +
      "(\t\022\020\n\010Keywords\030\002 \003(\t\022\033\n\023PositionPercenta" +
      "ges\030\003 \003(\002\"\210\001\n\031TextSummarizationTaskData\022" +
      "\017\n\007Summary\030\001 \001(\t\022\r\n\005Title\030\002 \001(\t\0229\n\tSente" +
      "nces\030\003 \003(\0132&.trpc.media.textsummarizatio" +
      "n.Sentence\022\020\n\010Keywords\030\004 \003(\tB\240\001\n\023com.ten" +
      "cent.aimediaB\031TextSummarizationProtocolZ" +
      "ngit.code.oa.com/yt-media-ai-videounders" +
      "tanding/yt-ai-media-middle-platform-api/" +
      "protobuf-spec/textsummarizationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_trpc_media_textsummarization_Sentence_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trpc_media_textsummarization_Sentence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trpc_media_textsummarization_Sentence_descriptor,
        new java.lang.String[] { "Text", "Keywords", "PositionPercentages", });
    internal_static_trpc_media_textsummarization_TextSummarizationTaskData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trpc_media_textsummarization_TextSummarizationTaskData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trpc_media_textsummarization_TextSummarizationTaskData_descriptor,
        new java.lang.String[] { "Summary", "Title", "Sentences", "Keywords", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
