// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_cut.proto

package com.tencent.aimedia;

public final class VideoCutProtocol {
  private VideoCutProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VideoCutTaskDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trpc.media.videocut.VideoCutTaskData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 VideocutSize = 4;</code>
     * @return The videocutSize.
     */
    int getVideocutSize();

    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    java.util.List<com.tencent.aimedia.VideoCutProtocol.VideoCutItem> 
        getVideocutItemsList();
    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    com.tencent.aimedia.VideoCutProtocol.VideoCutItem getVideocutItems(int index);
    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    int getVideocutItemsCount();
    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    java.util.List<? extends com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder> 
        getVideocutItemsOrBuilderList();
    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder getVideocutItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code trpc.media.videocut.VideoCutTaskData}
   */
  public static final class VideoCutTaskData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trpc.media.videocut.VideoCutTaskData)
      VideoCutTaskDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VideoCutTaskData.newBuilder() to construct.
    private VideoCutTaskData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VideoCutTaskData() {
      videocutItems_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VideoCutTaskData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutTaskData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutTaskData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData.class, com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData.Builder.class);
    }

    public static final int VIDEOCUTSIZE_FIELD_NUMBER = 4;
    private int videocutSize_;
    /**
     * <code>int32 VideocutSize = 4;</code>
     * @return The videocutSize.
     */
    @java.lang.Override
    public int getVideocutSize() {
      return videocutSize_;
    }

    public static final int VIDEOCUTITEMS_FIELD_NUMBER = 5;
    private java.util.List<com.tencent.aimedia.VideoCutProtocol.VideoCutItem> videocutItems_;
    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.tencent.aimedia.VideoCutProtocol.VideoCutItem> getVideocutItemsList() {
      return videocutItems_;
    }
    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder> 
        getVideocutItemsOrBuilderList() {
      return videocutItems_;
    }
    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    @java.lang.Override
    public int getVideocutItemsCount() {
      return videocutItems_.size();
    }
    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    @java.lang.Override
    public com.tencent.aimedia.VideoCutProtocol.VideoCutItem getVideocutItems(int index) {
      return videocutItems_.get(index);
    }
    /**
     * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
     */
    @java.lang.Override
    public com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder getVideocutItemsOrBuilder(
        int index) {
      return videocutItems_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (videocutSize_ != 0) {
        output.writeInt32(4, videocutSize_);
      }
      for (int i = 0; i < videocutItems_.size(); i++) {
        output.writeMessage(5, videocutItems_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (videocutSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, videocutSize_);
      }
      for (int i = 0; i < videocutItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, videocutItems_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData)) {
        return super.equals(obj);
      }
      com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData other = (com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData) obj;

      if (getVideocutSize()
          != other.getVideocutSize()) return false;
      if (!getVideocutItemsList()
          .equals(other.getVideocutItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VIDEOCUTSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getVideocutSize();
      if (getVideocutItemsCount() > 0) {
        hash = (37 * hash) + VIDEOCUTITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getVideocutItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trpc.media.videocut.VideoCutTaskData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trpc.media.videocut.VideoCutTaskData)
        com.tencent.aimedia.VideoCutProtocol.VideoCutTaskDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutTaskData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutTaskData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData.class, com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData.Builder.class);
      }

      // Construct using com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        videocutSize_ = 0;

        if (videocutItemsBuilder_ == null) {
          videocutItems_ = java.util.Collections.emptyList();
        } else {
          videocutItems_ = null;
          videocutItemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutTaskData_descriptor;
      }

      @java.lang.Override
      public com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData getDefaultInstanceForType() {
        return com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData build() {
        com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData buildPartial() {
        com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData result = new com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData(this);
        int from_bitField0_ = bitField0_;
        result.videocutSize_ = videocutSize_;
        if (videocutItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            videocutItems_ = java.util.Collections.unmodifiableList(videocutItems_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.videocutItems_ = videocutItems_;
        } else {
          result.videocutItems_ = videocutItemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData) {
          return mergeFrom((com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData other) {
        if (other == com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData.getDefaultInstance()) return this;
        if (other.getVideocutSize() != 0) {
          setVideocutSize(other.getVideocutSize());
        }
        if (videocutItemsBuilder_ == null) {
          if (!other.videocutItems_.isEmpty()) {
            if (videocutItems_.isEmpty()) {
              videocutItems_ = other.videocutItems_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureVideocutItemsIsMutable();
              videocutItems_.addAll(other.videocutItems_);
            }
            onChanged();
          }
        } else {
          if (!other.videocutItems_.isEmpty()) {
            if (videocutItemsBuilder_.isEmpty()) {
              videocutItemsBuilder_.dispose();
              videocutItemsBuilder_ = null;
              videocutItems_ = other.videocutItems_;
              bitField0_ = (bitField0_ & ~0x00000001);
              videocutItemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVideocutItemsFieldBuilder() : null;
            } else {
              videocutItemsBuilder_.addAllMessages(other.videocutItems_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 32: {
                videocutSize_ = input.readInt32();

                break;
              } // case 32
              case 42: {
                com.tencent.aimedia.VideoCutProtocol.VideoCutItem m =
                    input.readMessage(
                        com.tencent.aimedia.VideoCutProtocol.VideoCutItem.parser(),
                        extensionRegistry);
                if (videocutItemsBuilder_ == null) {
                  ensureVideocutItemsIsMutable();
                  videocutItems_.add(m);
                } else {
                  videocutItemsBuilder_.addMessage(m);
                }
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int videocutSize_ ;
      /**
       * <code>int32 VideocutSize = 4;</code>
       * @return The videocutSize.
       */
      @java.lang.Override
      public int getVideocutSize() {
        return videocutSize_;
      }
      /**
       * <code>int32 VideocutSize = 4;</code>
       * @param value The videocutSize to set.
       * @return This builder for chaining.
       */
      public Builder setVideocutSize(int value) {
        
        videocutSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 VideocutSize = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideocutSize() {
        
        videocutSize_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.tencent.aimedia.VideoCutProtocol.VideoCutItem> videocutItems_ =
        java.util.Collections.emptyList();
      private void ensureVideocutItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          videocutItems_ = new java.util.ArrayList<com.tencent.aimedia.VideoCutProtocol.VideoCutItem>(videocutItems_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.aimedia.VideoCutProtocol.VideoCutItem, com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder, com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder> videocutItemsBuilder_;

      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public java.util.List<com.tencent.aimedia.VideoCutProtocol.VideoCutItem> getVideocutItemsList() {
        if (videocutItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(videocutItems_);
        } else {
          return videocutItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public int getVideocutItemsCount() {
        if (videocutItemsBuilder_ == null) {
          return videocutItems_.size();
        } else {
          return videocutItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public com.tencent.aimedia.VideoCutProtocol.VideoCutItem getVideocutItems(int index) {
        if (videocutItemsBuilder_ == null) {
          return videocutItems_.get(index);
        } else {
          return videocutItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public Builder setVideocutItems(
          int index, com.tencent.aimedia.VideoCutProtocol.VideoCutItem value) {
        if (videocutItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVideocutItemsIsMutable();
          videocutItems_.set(index, value);
          onChanged();
        } else {
          videocutItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public Builder setVideocutItems(
          int index, com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder builderForValue) {
        if (videocutItemsBuilder_ == null) {
          ensureVideocutItemsIsMutable();
          videocutItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          videocutItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public Builder addVideocutItems(com.tencent.aimedia.VideoCutProtocol.VideoCutItem value) {
        if (videocutItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVideocutItemsIsMutable();
          videocutItems_.add(value);
          onChanged();
        } else {
          videocutItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public Builder addVideocutItems(
          int index, com.tencent.aimedia.VideoCutProtocol.VideoCutItem value) {
        if (videocutItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVideocutItemsIsMutable();
          videocutItems_.add(index, value);
          onChanged();
        } else {
          videocutItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public Builder addVideocutItems(
          com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder builderForValue) {
        if (videocutItemsBuilder_ == null) {
          ensureVideocutItemsIsMutable();
          videocutItems_.add(builderForValue.build());
          onChanged();
        } else {
          videocutItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public Builder addVideocutItems(
          int index, com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder builderForValue) {
        if (videocutItemsBuilder_ == null) {
          ensureVideocutItemsIsMutable();
          videocutItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          videocutItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public Builder addAllVideocutItems(
          java.lang.Iterable<? extends com.tencent.aimedia.VideoCutProtocol.VideoCutItem> values) {
        if (videocutItemsBuilder_ == null) {
          ensureVideocutItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, videocutItems_);
          onChanged();
        } else {
          videocutItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public Builder clearVideocutItems() {
        if (videocutItemsBuilder_ == null) {
          videocutItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          videocutItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public Builder removeVideocutItems(int index) {
        if (videocutItemsBuilder_ == null) {
          ensureVideocutItemsIsMutable();
          videocutItems_.remove(index);
          onChanged();
        } else {
          videocutItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder getVideocutItemsBuilder(
          int index) {
        return getVideocutItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder getVideocutItemsOrBuilder(
          int index) {
        if (videocutItemsBuilder_ == null) {
          return videocutItems_.get(index);  } else {
          return videocutItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public java.util.List<? extends com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder> 
           getVideocutItemsOrBuilderList() {
        if (videocutItemsBuilder_ != null) {
          return videocutItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(videocutItems_);
        }
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder addVideocutItemsBuilder() {
        return getVideocutItemsFieldBuilder().addBuilder(
            com.tencent.aimedia.VideoCutProtocol.VideoCutItem.getDefaultInstance());
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder addVideocutItemsBuilder(
          int index) {
        return getVideocutItemsFieldBuilder().addBuilder(
            index, com.tencent.aimedia.VideoCutProtocol.VideoCutItem.getDefaultInstance());
      }
      /**
       * <code>repeated .trpc.media.videocut.VideoCutItem VideocutItems = 5;</code>
       */
      public java.util.List<com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder> 
           getVideocutItemsBuilderList() {
        return getVideocutItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.aimedia.VideoCutProtocol.VideoCutItem, com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder, com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder> 
          getVideocutItemsFieldBuilder() {
        if (videocutItemsBuilder_ == null) {
          videocutItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tencent.aimedia.VideoCutProtocol.VideoCutItem, com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder, com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder>(
                  videocutItems_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          videocutItems_ = null;
        }
        return videocutItemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trpc.media.videocut.VideoCutTaskData)
    }

    // @@protoc_insertion_point(class_scope:trpc.media.videocut.VideoCutTaskData)
    private static final com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData();
    }

    public static com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VideoCutTaskData>
        PARSER = new com.google.protobuf.AbstractParser<VideoCutTaskData>() {
      @java.lang.Override
      public VideoCutTaskData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VideoCutTaskData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VideoCutTaskData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.aimedia.VideoCutProtocol.VideoCutTaskData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VideoCutItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trpc.media.videocut.VideoCutItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 切片类型
     * </pre>
     *
     * <code>string VideocutType = 1;</code>
     * @return The videocutType.
     */
    java.lang.String getVideocutType();
    /**
     * <pre>
     * 切片类型
     * </pre>
     *
     * <code>string VideocutType = 1;</code>
     * @return The bytes for videocutType.
     */
    com.google.protobuf.ByteString
        getVideocutTypeBytes();

    /**
     * <pre>
     * 镜头起始帧
     * </pre>
     *
     * <code>int32 HeadIndex = 2;</code>
     * @return The headIndex.
     */
    int getHeadIndex();

    /**
     * <pre>
     * 镜头终止帧
     * </pre>
     *
     * <code>int32 TailIndex = 3;</code>
     * @return The tailIndex.
     */
    int getTailIndex();

    /**
     * <pre>
     * 镜头起始时间
     * </pre>
     *
     * <code>float StartTime = 4;</code>
     * @return The startTime.
     */
    float getStartTime();

    /**
     * <pre>
     * 镜头终止时间
     * </pre>
     *
     * <code>float EndTime = 5;</code>
     * @return The endTime.
     */
    float getEndTime();
  }
  /**
   * Protobuf type {@code trpc.media.videocut.VideoCutItem}
   */
  public static final class VideoCutItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trpc.media.videocut.VideoCutItem)
      VideoCutItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VideoCutItem.newBuilder() to construct.
    private VideoCutItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VideoCutItem() {
      videocutType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VideoCutItem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.aimedia.VideoCutProtocol.VideoCutItem.class, com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder.class);
    }

    public static final int VIDEOCUTTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object videocutType_;
    /**
     * <pre>
     * 切片类型
     * </pre>
     *
     * <code>string VideocutType = 1;</code>
     * @return The videocutType.
     */
    @java.lang.Override
    public java.lang.String getVideocutType() {
      java.lang.Object ref = videocutType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        videocutType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 切片类型
     * </pre>
     *
     * <code>string VideocutType = 1;</code>
     * @return The bytes for videocutType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVideocutTypeBytes() {
      java.lang.Object ref = videocutType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videocutType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADINDEX_FIELD_NUMBER = 2;
    private int headIndex_;
    /**
     * <pre>
     * 镜头起始帧
     * </pre>
     *
     * <code>int32 HeadIndex = 2;</code>
     * @return The headIndex.
     */
    @java.lang.Override
    public int getHeadIndex() {
      return headIndex_;
    }

    public static final int TAILINDEX_FIELD_NUMBER = 3;
    private int tailIndex_;
    /**
     * <pre>
     * 镜头终止帧
     * </pre>
     *
     * <code>int32 TailIndex = 3;</code>
     * @return The tailIndex.
     */
    @java.lang.Override
    public int getTailIndex() {
      return tailIndex_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 4;
    private float startTime_;
    /**
     * <pre>
     * 镜头起始时间
     * </pre>
     *
     * <code>float StartTime = 4;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public float getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 5;
    private float endTime_;
    /**
     * <pre>
     * 镜头终止时间
     * </pre>
     *
     * <code>float EndTime = 5;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public float getEndTime() {
      return endTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(videocutType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, videocutType_);
      }
      if (headIndex_ != 0) {
        output.writeInt32(2, headIndex_);
      }
      if (tailIndex_ != 0) {
        output.writeInt32(3, tailIndex_);
      }
      if (java.lang.Float.floatToRawIntBits(startTime_) != 0) {
        output.writeFloat(4, startTime_);
      }
      if (java.lang.Float.floatToRawIntBits(endTime_) != 0) {
        output.writeFloat(5, endTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(videocutType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, videocutType_);
      }
      if (headIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, headIndex_);
      }
      if (tailIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, tailIndex_);
      }
      if (java.lang.Float.floatToRawIntBits(startTime_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, startTime_);
      }
      if (java.lang.Float.floatToRawIntBits(endTime_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, endTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.aimedia.VideoCutProtocol.VideoCutItem)) {
        return super.equals(obj);
      }
      com.tencent.aimedia.VideoCutProtocol.VideoCutItem other = (com.tencent.aimedia.VideoCutProtocol.VideoCutItem) obj;

      if (!getVideocutType()
          .equals(other.getVideocutType())) return false;
      if (getHeadIndex()
          != other.getHeadIndex()) return false;
      if (getTailIndex()
          != other.getTailIndex()) return false;
      if (java.lang.Float.floatToIntBits(getStartTime())
          != java.lang.Float.floatToIntBits(
              other.getStartTime())) return false;
      if (java.lang.Float.floatToIntBits(getEndTime())
          != java.lang.Float.floatToIntBits(
              other.getEndTime())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VIDEOCUTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getVideocutType().hashCode();
      hash = (37 * hash) + HEADINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getHeadIndex();
      hash = (37 * hash) + TAILINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getTailIndex();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStartTime());
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getEndTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.aimedia.VideoCutProtocol.VideoCutItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trpc.media.videocut.VideoCutItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trpc.media.videocut.VideoCutItem)
        com.tencent.aimedia.VideoCutProtocol.VideoCutItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.aimedia.VideoCutProtocol.VideoCutItem.class, com.tencent.aimedia.VideoCutProtocol.VideoCutItem.Builder.class);
      }

      // Construct using com.tencent.aimedia.VideoCutProtocol.VideoCutItem.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        videocutType_ = "";

        headIndex_ = 0;

        tailIndex_ = 0;

        startTime_ = 0F;

        endTime_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.aimedia.VideoCutProtocol.internal_static_trpc_media_videocut_VideoCutItem_descriptor;
      }

      @java.lang.Override
      public com.tencent.aimedia.VideoCutProtocol.VideoCutItem getDefaultInstanceForType() {
        return com.tencent.aimedia.VideoCutProtocol.VideoCutItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.aimedia.VideoCutProtocol.VideoCutItem build() {
        com.tencent.aimedia.VideoCutProtocol.VideoCutItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.aimedia.VideoCutProtocol.VideoCutItem buildPartial() {
        com.tencent.aimedia.VideoCutProtocol.VideoCutItem result = new com.tencent.aimedia.VideoCutProtocol.VideoCutItem(this);
        result.videocutType_ = videocutType_;
        result.headIndex_ = headIndex_;
        result.tailIndex_ = tailIndex_;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.aimedia.VideoCutProtocol.VideoCutItem) {
          return mergeFrom((com.tencent.aimedia.VideoCutProtocol.VideoCutItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.aimedia.VideoCutProtocol.VideoCutItem other) {
        if (other == com.tencent.aimedia.VideoCutProtocol.VideoCutItem.getDefaultInstance()) return this;
        if (!other.getVideocutType().isEmpty()) {
          videocutType_ = other.videocutType_;
          onChanged();
        }
        if (other.getHeadIndex() != 0) {
          setHeadIndex(other.getHeadIndex());
        }
        if (other.getTailIndex() != 0) {
          setTailIndex(other.getTailIndex());
        }
        if (other.getStartTime() != 0F) {
          setStartTime(other.getStartTime());
        }
        if (other.getEndTime() != 0F) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                videocutType_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 16: {
                headIndex_ = input.readInt32();

                break;
              } // case 16
              case 24: {
                tailIndex_ = input.readInt32();

                break;
              } // case 24
              case 37: {
                startTime_ = input.readFloat();

                break;
              } // case 37
              case 45: {
                endTime_ = input.readFloat();

                break;
              } // case 45
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object videocutType_ = "";
      /**
       * <pre>
       * 切片类型
       * </pre>
       *
       * <code>string VideocutType = 1;</code>
       * @return The videocutType.
       */
      public java.lang.String getVideocutType() {
        java.lang.Object ref = videocutType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          videocutType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 切片类型
       * </pre>
       *
       * <code>string VideocutType = 1;</code>
       * @return The bytes for videocutType.
       */
      public com.google.protobuf.ByteString
          getVideocutTypeBytes() {
        java.lang.Object ref = videocutType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videocutType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 切片类型
       * </pre>
       *
       * <code>string VideocutType = 1;</code>
       * @param value The videocutType to set.
       * @return This builder for chaining.
       */
      public Builder setVideocutType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        videocutType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 切片类型
       * </pre>
       *
       * <code>string VideocutType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideocutType() {
        
        videocutType_ = getDefaultInstance().getVideocutType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 切片类型
       * </pre>
       *
       * <code>string VideocutType = 1;</code>
       * @param value The bytes for videocutType to set.
       * @return This builder for chaining.
       */
      public Builder setVideocutTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        videocutType_ = value;
        onChanged();
        return this;
      }

      private int headIndex_ ;
      /**
       * <pre>
       * 镜头起始帧
       * </pre>
       *
       * <code>int32 HeadIndex = 2;</code>
       * @return The headIndex.
       */
      @java.lang.Override
      public int getHeadIndex() {
        return headIndex_;
      }
      /**
       * <pre>
       * 镜头起始帧
       * </pre>
       *
       * <code>int32 HeadIndex = 2;</code>
       * @param value The headIndex to set.
       * @return This builder for chaining.
       */
      public Builder setHeadIndex(int value) {
        
        headIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 镜头起始帧
       * </pre>
       *
       * <code>int32 HeadIndex = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadIndex() {
        
        headIndex_ = 0;
        onChanged();
        return this;
      }

      private int tailIndex_ ;
      /**
       * <pre>
       * 镜头终止帧
       * </pre>
       *
       * <code>int32 TailIndex = 3;</code>
       * @return The tailIndex.
       */
      @java.lang.Override
      public int getTailIndex() {
        return tailIndex_;
      }
      /**
       * <pre>
       * 镜头终止帧
       * </pre>
       *
       * <code>int32 TailIndex = 3;</code>
       * @param value The tailIndex to set.
       * @return This builder for chaining.
       */
      public Builder setTailIndex(int value) {
        
        tailIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 镜头终止帧
       * </pre>
       *
       * <code>int32 TailIndex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTailIndex() {
        
        tailIndex_ = 0;
        onChanged();
        return this;
      }

      private float startTime_ ;
      /**
       * <pre>
       * 镜头起始时间
       * </pre>
       *
       * <code>float StartTime = 4;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public float getStartTime() {
        return startTime_;
      }
      /**
       * <pre>
       * 镜头起始时间
       * </pre>
       *
       * <code>float StartTime = 4;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(float value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 镜头起始时间
       * </pre>
       *
       * <code>float StartTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        
        startTime_ = 0F;
        onChanged();
        return this;
      }

      private float endTime_ ;
      /**
       * <pre>
       * 镜头终止时间
       * </pre>
       *
       * <code>float EndTime = 5;</code>
       * @return The endTime.
       */
      @java.lang.Override
      public float getEndTime() {
        return endTime_;
      }
      /**
       * <pre>
       * 镜头终止时间
       * </pre>
       *
       * <code>float EndTime = 5;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(float value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 镜头终止时间
       * </pre>
       *
       * <code>float EndTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        
        endTime_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trpc.media.videocut.VideoCutItem)
    }

    // @@protoc_insertion_point(class_scope:trpc.media.videocut.VideoCutItem)
    private static final com.tencent.aimedia.VideoCutProtocol.VideoCutItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.aimedia.VideoCutProtocol.VideoCutItem();
    }

    public static com.tencent.aimedia.VideoCutProtocol.VideoCutItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VideoCutItem>
        PARSER = new com.google.protobuf.AbstractParser<VideoCutItem>() {
      @java.lang.Override
      public VideoCutItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VideoCutItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VideoCutItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.aimedia.VideoCutProtocol.VideoCutItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trpc_media_videocut_VideoCutTaskData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trpc_media_videocut_VideoCutTaskData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trpc_media_videocut_VideoCutItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trpc_media_videocut_VideoCutItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017video_cut.proto\022\023trpc.media.videocut\"b" +
      "\n\020VideoCutTaskData\022\024\n\014VideocutSize\030\004 \001(\005" +
      "\0228\n\rVideocutItems\030\005 \003(\0132!.trpc.media.vid" +
      "eocut.VideoCutItem\"n\n\014VideoCutItem\022\024\n\014Vi" +
      "deocutType\030\001 \001(\t\022\021\n\tHeadIndex\030\002 \001(\005\022\021\n\tT" +
      "ailIndex\030\003 \001(\005\022\021\n\tStartTime\030\004 \001(\002\022\017\n\007End" +
      "Time\030\005 \001(\002B\216\001\n\023com.tencent.aimediaB\020Vide" +
      "oCutProtocolZegit.code.oa.com/yt-media-a" +
      "i-videounderstanding/yt-ai-media-middle-" +
      "platform-api/protobuf-spec/videocutb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_trpc_media_videocut_VideoCutTaskData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trpc_media_videocut_VideoCutTaskData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trpc_media_videocut_VideoCutTaskData_descriptor,
        new java.lang.String[] { "VideocutSize", "VideocutItems", });
    internal_static_trpc_media_videocut_VideoCutItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trpc_media_videocut_VideoCutItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trpc_media_videocut_VideoCutItem_descriptor,
        new java.lang.String[] { "VideocutType", "HeadIndex", "TailIndex", "StartTime", "EndTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
