package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;
import java.util.concurrent.CompletionStage;

import com.tencent.aimedia.VideoQualityEvaluationProtocol.CreateVideoQualityEvaluationTaskRequest;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.CreateVideoQualityEvaluationTaskResponse;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeVideoQualityEvaluationTaskDataRequest;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeVideoQualityEvaluationTaskDataResponse;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeLiveVideoQualityEvaluationTaskDataResponse;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeVideoQualityLimitListRequest;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeVideoQualityLimitListResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.videoquality.VideoQualityEvaluation")
public interface VideoQualityEvaluationAsyncAPI {

    /**
     * CreateVideoQualityEvaluationTask
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link CreateVideoQualityEvaluationTaskResponse}
     */
    @TRpcMethod(name = "CreateVideoQualityEvaluationTask")
    CompletionStage<CreateVideoQualityEvaluationTaskResponse> createVideoQualityEvaluationTask(RpcContext context, CreateVideoQualityEvaluationTaskRequest request);

    /**
     * DescribeVideoQualityEvaluationTaskData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeVideoQualityEvaluationTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeVideoQualityEvaluationTaskData")
    CompletionStage<DescribeVideoQualityEvaluationTaskDataResponse> describeVideoQualityEvaluationTaskData(RpcContext context, DescribeVideoQualityEvaluationTaskDataRequest request);

    /**
     * DescribeLiveVideoQualityEvaluationTaskData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeLiveVideoQualityEvaluationTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeLiveVideoQualityEvaluationTaskData")
    CompletionStage<DescribeLiveVideoQualityEvaluationTaskDataResponse> describeLiveVideoQualityEvaluationTaskData(RpcContext context, DescribeVideoQualityEvaluationTaskDataRequest request);

    /**
     * DescribeVideoQualityLimitList
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link DescribeVideoQualityLimitListResponse}
     */
    @TRpcMethod(name = "DescribeVideoQualityLimitList")
    CompletionStage<DescribeVideoQualityLimitListResponse> describeVideoQualityLimitList(RpcContext context, DescribeVideoQualityLimitListRequest request);
}