package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.VideoQualityEvaluationProtocol.CreateVideoQualityEvaluationTaskRequest;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.CreateVideoQualityEvaluationTaskResponse;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeVideoQualityEvaluationTaskDataRequest;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeVideoQualityEvaluationTaskDataResponse;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeLiveVideoQualityEvaluationTaskDataResponse;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeVideoQualityLimitListRequest;
import com.tencent.aimedia.VideoQualityEvaluationProtocol.DescribeVideoQualityLimitListResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.videoquality.VideoQualityEvaluation")
public interface VideoQualityEvaluationAPI {

    /**
     * CreateVideoQualityEvaluationTask
     *
     * @param context context
     * @param request request
     * @return {@link CreateVideoQualityEvaluationTaskResponse}
     */
    @TRpcMethod(name = "CreateVideoQualityEvaluationTask")
    CreateVideoQualityEvaluationTaskResponse createVideoQualityEvaluationTask(RpcContext context, CreateVideoQualityEvaluationTaskRequest request);

    /**
     * DescribeVideoQualityEvaluationTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribeVideoQualityEvaluationTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeVideoQualityEvaluationTaskData")
    DescribeVideoQualityEvaluationTaskDataResponse describeVideoQualityEvaluationTaskData(RpcContext context, DescribeVideoQualityEvaluationTaskDataRequest request);

    /**
     * DescribeLiveVideoQualityEvaluationTaskData
     *
     * @param context context
     * @param request request
     * @return {@link DescribeLiveVideoQualityEvaluationTaskDataResponse}
     */
    @TRpcMethod(name = "DescribeLiveVideoQualityEvaluationTaskData")
    DescribeLiveVideoQualityEvaluationTaskDataResponse describeLiveVideoQualityEvaluationTaskData(RpcContext context, DescribeVideoQualityEvaluationTaskDataRequest request);

    /**
     * DescribeVideoQualityLimitList
     *
     * @param context context
     * @param request request
     * @return {@link DescribeVideoQualityLimitListResponse}
     */
    @TRpcMethod(name = "DescribeVideoQualityLimitList")
    DescribeVideoQualityLimitListResponse describeVideoQualityLimitList(RpcContext context, DescribeVideoQualityLimitListRequest request);
}