package com.tencent.aimedia;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;

import com.tencent.aimedia.YTVideoProcessProtocol.CreateVideoProcessTaskRequest;
import com.tencent.aimedia.YTVideoProcessProtocol.CreateVideoProcessResponse;
import com.tencent.aimedia.YTVideoProcessProtocol.DescribeVideoProcessDetailRequest;
import com.tencent.aimedia.YTVideoProcessProtocol.DescribeVideoProcessDetailResponse;
import com.tencent.aimedia.YTVideoProcessProtocol.UpdateVideoProcessTaskRequest;
import com.tencent.aimedia.YTVideoProcessProtocol.UpdateVideoProcessResponse;
import com.tencent.aimedia.YTVideoProcessProtocol.StopVideoProcessTaskRequest;
import com.tencent.aimedia.YTVideoProcessProtocol.StopVideoProcessTaskResponse;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.media.ytvideoprocess.YTVideoProcess")
public interface YTVideoProcessAPI {

    /**
     * CreateVideoProcessTask
     *
     * @param context context
     * @param request request
     * @return {@link CreateVideoProcessResponse}
     */
    @TRpcMethod(name = "CreateVideoProcessTask")
    CreateVideoProcessResponse createVideoProcessTask(RpcContext context, CreateVideoProcessTaskRequest request);

    /**
     * DescribeVideoProcessDetail
     *
     * @param context context
     * @param request request
     * @return {@link DescribeVideoProcessDetailResponse}
     */
    @TRpcMethod(name = "DescribeVideoProcessDetail")
    DescribeVideoProcessDetailResponse describeVideoProcessDetail(RpcContext context, DescribeVideoProcessDetailRequest request);

    /**
     * UpdateVideoProcessTask
     *
     * @param context context
     * @param request request
     * @return {@link UpdateVideoProcessResponse}
     */
    @TRpcMethod(name = "UpdateVideoProcessTask")
    UpdateVideoProcessResponse updateVideoProcessTask(RpcContext context, UpdateVideoProcessTaskRequest request);

    /**
     * StopVideoProcessTask
     *
     * @param context context
     * @param request request
     * @return {@link StopVideoProcessTaskResponse}
     */
    @TRpcMethod(name = "StopVideoProcessTask")
    StopVideoProcessTaskResponse stopVideoProcessTask(RpcContext context, StopVideoProcessTaskRequest request);
}